export const AppLocales = ['ja-JP'] as const
export type AppLocale = (typeof AppLocales)[number]

export const InternalPseudoLocale = 'en-XA' as const
export type LocalizationLocale = AppLocale | typeof InternalPseudoLocale

export type MessageParameter = string | number
export type MessageParameters = Readonly<Record<string, MessageParameter>>

export const JapaneseMessages = Object.freeze({
  'app.name': '甲ブラウザ',
  'common.cancel': 'キャンセル',
  'assistDiagnostic.button': '診断情報を保存',
  'assistDiagnostic.dialogTitle': 'アシスト画面の診断情報を保存',
  'assistDiagnostic.failed':
    '診断情報を保存できませんでした。別の保存先またはファイル名でもう一度お試しください。',
  'assistDiagnostic.saved': '{fileName} に識別情報を除いた診断情報を保存しました。',
  'assistDiagnostic.saving': '診断情報を作成しています...',
  'taihaProtection.acknowledge': 'Ctrl + クリックで保護を解除',
  'taihaProtection.description':
    '大破艦を検出したため、ゲーム画面への入力を保護しています。撤退を選ぶ場合も、内容を確認してから保護を解除してください。',
  'taihaProtection.heading': '大破艦があります',
  'taihaProtection.hint': 'キーボード操作では Ctrl + Enter でも解除できます。',
  'accountBackup.button': '現在のアカウントをバックアップ',
  'accountBackup.cancelled': 'バックアップをキャンセルしました。',
  'accountBackup.created':
    '{bundleName} を作成しました（DB {databaseFiles}、設定 {profileFiles}、記録 {records} 件）。',
  'accountBackup.creating': 'バックアップを作成・検証しています...',
  'accountBackup.description':
    '現在のアカウントの記録 DB とアカウント別設定を、検証可能な新しいフォルダへ保存します。',
  'accountBackup.dialogTitle': 'ローカルバックアップの保存先を選択',
  'accountBackup.failed':
    'バックアップを作成できませんでした。保存先と空き容量を確認して、もう一度お試しください。',
  'accountBackup.heading': 'ローカルバックアップ',
  'accountBackup.transfer.button': '暗号化 transfer を保存',
  'accountBackup.transfer.cancelled': '暗号化 transfer の保存をキャンセルしました。',
  'accountBackup.transfer.confirmPassphrase': '合言葉（確認）',
  'accountBackup.transfer.created': '{fileName} に暗号化 transfer を保存しました（{records} 件）。',
  'accountBackup.transfer.creating': '整合 snapshot を作成し、暗号化と自己検証を行っています...',
  'accountBackup.transfer.description':
    '現在のアカウントデータを、別 PC へ安全に移すための単一暗号化ファイルとして保存します。',
  'accountBackup.transfer.dialogTitle': '暗号化 transfer の保存先を選択',
  'accountBackup.transfer.failed':
    '暗号化 transfer を作成できませんでした。保存先、空き容量、合言葉を確認してください。',
  'accountBackup.transfer.fileType': '甲ブラウザ暗号化 transfer',
  'accountBackup.transfer.heading': '暗号化共有用エクスポート',
  'accountBackup.transfer.importButton': '暗号化 transfer を検査',
  'accountBackup.transfer.importDescription':
    '別 PC で作成した暗号化 transfer を開き、既存の読み取り専用 preview、統合、復元手順へ渡します。',
  'accountBackup.transfer.importHeading': '暗号化 transfer の読み込み',
  'accountBackup.transfer.importPassphrase': 'transfer の合言葉',
  'accountBackup.transfer.inspectDialogTitle': '検査する暗号化 transfer を選択',
  'accountBackup.transfer.invalid':
    '合言葉が違うか、transfer が破損・未対応です。現在のデータは変更されていません。',
  'accountBackup.transfer.mismatch': '合言葉が一致していません。',
  'accountBackup.transfer.passphrase': '合言葉',
  'accountBackup.transfer.passphraseHint':
    '12 文字以上の長い合言葉を入力してください。文字種の制限はありません。',
  'accountBackup.transfer.warning':
    '合言葉は保存されず、忘れた場合は復旧できません。transfer ファイルと合言葉は別の経路で共有してください。',
  'accountBackup.audit.captureButton': '現在データの基準を保存',
  'accountBackup.audit.captured':
    '{capturedAt} の基準を保存しました（DB {databaseFiles}、設定 {profileFiles}、記録 {records} 件）。',
  'accountBackup.audit.capturing': '記録 DB とアカウント設定を読み取り専用で検査しています...',
  'accountBackup.audit.compareButton': '保存した基準と比較',
  'accountBackup.audit.comparing': '保存した基準と現在のデータを比較しています...',
  'accountBackup.audit.database': 'DB',
  'accountBackup.audit.description':
    '現在の記録件数と内容の指紋を、個人情報や保存先を画面に出さない検査基準として保存できます。記録 DB は書き換えません。復元・元に戻す・再適用の前後で比較してください。',
  'accountBackup.audit.different':
    '保存した基準との差分があります。変更 DB: {databases}、変更設定: {profiles}。',
  'accountBackup.audit.differentAccount': '{capturedAt} の基準は現在のアカウント用ではありません。',
  'accountBackup.audit.failed':
    'データ整合性を検査できませんでした。アカウントデータの読み込み後に、もう一度お試しください。',
  'accountBackup.audit.heading': '復元データ整合性',
  'accountBackup.audit.match':
    '現在のデータは {capturedAt} の基準と一致します（DB {databaseFiles}、設定 {profileFiles}、記録 {records} 件）。',
  'accountBackup.audit.noChanges': 'なし',
  'accountBackup.audit.none': '保存済みの検査基準がありません。',
  'accountBackup.audit.records': '記録件数',
  'accountBackup.inspect.button': 'バックアップを検査',
  'accountBackup.inspect.cancelled': 'バックアップの検査をキャンセルしました。',
  'accountBackup.inspect.description':
    '既存のバックアップフォルダを読み取り専用で検査します。復元やデータ変更は行いません。',
  'accountBackup.inspect.dialogTitle': '検査するバックアップフォルダを選択',
  'accountBackup.inspect.failed': 'バックアップを検査できませんでした。もう一度お試しください。',
  'accountBackup.inspect.inspecting':
    'manifest、ファイルサイズ、SHA-256、記録件数を検査しています...',
  'accountBackup.inspect.invalid':
    '有効なバックアップとして確認できませんでした。破損、不完全、または未対応の形式です。',
  'accountBackup.inspect.match.different':
    '現在ログイン中のアカウントとは一致しません。復元対象にはできません。',
  'accountBackup.inspect.match.same': '現在ログイン中のアカウントと一致します。',
  'accountBackup.inspect.match.unavailable':
    '現在のアカウントが未確定のため、アカウント一致を確認できません。',
  'accountBackup.inspect.preview.add': '追加候補',
  'accountBackup.inspect.preview.conflict': '内容競合',
  'accountBackup.inspect.preview.conflictGroup.context': '実行時情報',
  'accountBackup.inspect.preview.conflictGroup.display': '表示情報',
  'accountBackup.inspect.preview.conflictGroup.fleet': '艦隊',
  'accountBackup.inspect.preview.conflictGroup.identity': '記録ID',
  'accountBackup.inspect.preview.conflictGroup.input': '投入内容',
  'accountBackup.inspect.preview.conflictGroup.location': '海域・位置',
  'accountBackup.inspect.preview.conflictGroup.provenance': '作成元',
  'accountBackup.inspect.preview.conflictGroup.raw-response': '戦闘応答',
  'accountBackup.inspect.preview.conflictGroup.result': '結果',
  'accountBackup.inspect.preview.conflictGroup.reward': '報酬',
  'accountBackup.inspect.preview.conflictGroup.snapshot': 'スナップショット',
  'accountBackup.inspect.preview.conflictGroup.timestamp': '時刻',
  'accountBackup.inspect.preview.conflictGroup.unknown-field': '未対応項目',
  'accountBackup.inspect.preview.currentOnly': '現在のみ',
  'accountBackup.inspect.preview.database': 'DB',
  'accountBackup.inspect.preview.description':
    '同じアカウントの DB を読み取り専用で比較しました。安定した記録識別子を持つ新規記録と、同じ任務・周期・計数構造で単調に進んだ任務カウンタだけを安全統合します。任務カウンタは加算せず項目ごとの最大値を使い、内容競合、識別子のない旧記録、任務の別周期・未知構造は現在側を保持して要確認に分類します。まだ統合は行いません。',
  'accountBackup.inspect.preview.duplicate': '完全一致',
  'accountBackup.inspect.preview.incoming': 'バックアップ内',
  'accountBackup.inspect.preview.legacyDuplicate': '旧ID内容一致',
  'accountBackup.inspect.preview.manualReview': '要確認',
  'accountBackup.inspect.preview.safeAdd': '安全統合',
  'accountBackup.inspect.report.button': '識別情報を除いた検査記録を保存',
  'accountBackup.inspect.report.cancelled': '検査記録の保存をキャンセルしました。',
  'accountBackup.inspect.report.description':
    'Phase A の受け入れ証拠として、build、実行環境、作成日時、DB 件数、比較結果だけを JSON に保存します。アカウント・端末・bundle の識別子、パス、hash、raw record は含みません。',
  'accountBackup.inspect.report.dialogTitle': '識別情報を除いたアカウント検査記録を保存',
  'accountBackup.inspect.report.failed':
    '検査記録を保存できませんでした。既存ファイルを上書きせず、別のファイル名でもう一度お試しください。',
  'accountBackup.inspect.report.saved': '{fileName} に識別情報を除いた検査記録を保存しました。',
  'accountBackup.inspect.report.saving': '識別情報を除いた検査記録を保存しています...',
  'accountBackup.inspect.valid':
    '{bundleName} は有効です。作成: {createdAt}、アプリ: {appVersion}、DB {databaseFiles}、設定 {profileFiles}、記録 {records} 件。',
  'accountBackup.restore.recoveryFailed':
    '復元処理の途中状態を安全に回復できませんでした。現在のデータを上書きせず停止しています。甲ブラウザを終了し、restore-staging と restore-rollbacks を削除せずに保管してください。',
  'accountBackup.restore.recoveryFailedTitle': 'アカウントデータ復元エラー',
  'accountBackup.merge.recoveryFailed':
    'データ統合の回復に失敗しました。現在データを開かず、統合候補と回復用データを保持しました。',
  'accountBackup.merge.recoveryFailedTitle': 'アカウントデータ統合エラー',
  'accountBackup.merge.button': '安全な記録を統合',
  'accountBackup.merge.confirmButton': '統合を準備して再起動',
  'accountBackup.merge.confirmDetail':
    '安全と判定された新規記録と、同じ周期の任務カウンタの単調な進捗だけを取り込みます。任務の進捗は加算せず項目ごとの最大値を使います。内容競合・要確認・任務の別周期や未知構造は取り込まず、現在の記録を保持します。候補と現在データを再検証し、現在のデータは回復用にそのまま保管します。',
  'accountBackup.merge.confirmMessage': '安全統合と判定された記録と任務進捗を統合しますか？',
  'accountBackup.merge.confirmTitle': 'アカウントデータの統合',
  'accountBackup.merge.description':
    '安全な新規記録と、同じ周期・計数構造の任務カウンタの単調な進捗だけを取り込みます。内容競合・要確認・任務の別周期や未知構造は現在のデータを維持します。',
  'accountBackup.merge.failed':
    '統合を準備できませんでした。現在のデータは変更されていません。バックアップをもう一度検査してください。',
  'accountBackup.merge.noSafeAdd': '安全に統合できる記録や任務進捗はありません。',
  'accountBackup.merge.scheduled':
    '{bundleName} の安全な記録と任務進捗を統合する準備ができました。甲ブラウザを再起動します...',
  'accountBackup.mergeRollback.available':
    '統合前のデータが保管されています（作成: {createdAt}、識別子: {bundleName}）。',
  'accountBackup.mergeRollback.button': '統合前のデータへ戻す',
  'accountBackup.mergeRollback.checkButton': '統合前データを確認',
  'accountBackup.mergeRollback.checkFailed':
    '統合前のデータを確認できませんでした。もう一度お試しください。',
  'accountBackup.mergeRollback.confirmButton': '統合を元に戻して再起動',
  'accountBackup.mergeRollback.confirmDetail':
    '現在のアカウント記録を、安全な統合を行う直前の内容へ戻します。現在のデータは再適用用として削除せず保管されます。',
  'accountBackup.mergeRollback.confirmMessage': '安全な記録の統合を元に戻しますか？',
  'accountBackup.mergeRollback.confirmTitle': 'データ統合を元に戻す',
  'accountBackup.mergeRollback.failed':
    '統合を元に戻す準備ができませんでした。現在のデータは変更されていません。',
  'accountBackup.mergeRollback.loading': '統合前のデータを確認しています...',
  'accountBackup.mergeRollback.none': '利用できる統合前データはありません。',
  'accountBackup.mergeRollback.recoveryFailed':
    '統合を元に戻す途中状態を安全に回復できませんでした。データを上書きせず停止しています。merge-rollbacks を削除せずに保管してください。',
  'accountBackup.mergeRollback.recoveryFailedTitle': 'データ統合のロールバックエラー',
  'accountBackup.mergeRollback.scheduled':
    '{bundleName} の統合前データへ戻す準備ができました。甲ブラウザを再起動します...',
  'accountBackup.mergeRedo.available':
    '再適用できる統合後データが保管されています（作成: {createdAt}、識別子: {bundleName}）。',
  'accountBackup.mergeRedo.button': '統合後のデータを再適用',
  'accountBackup.mergeRedo.checkButton': '統合後データを確認',
  'accountBackup.mergeRedo.checkFailed':
    '統合後のデータを確認できませんでした。もう一度お試しください。',
  'accountBackup.mergeRedo.confirmButton': '統合を再適用して再起動',
  'accountBackup.mergeRedo.confirmDetail':
    '元に戻す直前に使用していた統合後のアカウント記録へ切り替えます。現在のデータは新しいロールバック用として削除せず保管されます。',
  'accountBackup.mergeRedo.confirmMessage': '安全な記録の統合を再適用しますか？',
  'accountBackup.mergeRedo.confirmTitle': 'データ統合を再適用',
  'accountBackup.mergeRedo.failed':
    '統合を再適用する準備ができませんでした。現在のデータは変更されていません。',
  'accountBackup.mergeRedo.loading': '再適用できる統合後データを確認しています...',
  'accountBackup.mergeRedo.none': '利用できる統合後データはありません。',
  'accountBackup.mergeRedo.recoveryFailed':
    '統合の再適用途中状態を安全に回復できませんでした。データを上書きせず停止しています。merge-rollbacks を削除せずに保管してください。',
  'accountBackup.mergeRedo.recoveryFailedTitle': 'データ統合の再適用エラー',
  'accountBackup.mergeRedo.scheduled':
    '{bundleName} の統合後データを再適用する準備ができました。甲ブラウザを再起動します...',
  'accountBackup.restore.confirmButton': '復元を準備して再起動',
  'accountBackup.restore.confirmDetail':
    '現在のアカウント記録と設定を、検査したバックアップの内容で完全に置き換えます。現在のデータはロールバック用にそのまま保管されます。再起動後の切り替えと検証が完了するまで、甲ブラウザを終了したり保存フォルダを変更したりしないでください。',
  'accountBackup.restore.confirmMessage': '検査したバックアップから復元しますか？',
  'accountBackup.restore.confirmTitle': 'アカウントデータの復元',
  'accountBackup.restore.failed':
    '復元を準備できませんでした。現在のデータは変更されていません。バックアップをもう一度検査してください。',
  'accountBackup.restore.scheduled':
    '{bundleName} からの復元を準備しました。甲ブラウザを再起動します...',
  'accountBackup.rollback.button': '復元前のデータへ戻す',
  'accountBackup.rollback.available':
    '復元前のデータが保管されています（作成: {createdAt}、識別子: {bundleName}）。',
  'accountBackup.rollback.checkButton': '復元前データを確認',
  'accountBackup.rollback.checkFailed':
    '復元前のデータを確認できませんでした。もう一度お試しください。',
  'accountBackup.rollback.confirmButton': '元に戻して再起動',
  'accountBackup.rollback.confirmDetail':
    '現在のアカウント記録と設定を、復元直前に保管した内容へ完全に戻します。現在のデータも再適用用として削除せず保管されます。再起動後の切り替えと検証が完了するまで、甲ブラウザを終了したり保存フォルダを変更したりしないでください。',
  'accountBackup.rollback.confirmMessage': '復元前に保管したアカウントデータへ戻しますか？',
  'accountBackup.rollback.confirmTitle': 'アカウントデータを元に戻す',
  'accountBackup.rollback.failed':
    '元に戻す処理を準備できませんでした。現在のデータは変更されていません。',
  'accountBackup.rollback.loading': '復元前のデータを確認しています...',
  'accountBackup.rollback.none': '利用できる復元前データはありません。',
  'accountBackup.rollback.recoveryFailed':
    '元に戻す処理の途中状態を安全に回復できませんでした。データを上書きせず停止しています。甲ブラウザを終了し、restore-rollbacks を削除せずに保管してください。',
  'accountBackup.rollback.recoveryFailedTitle': 'アカウントデータのロールバックエラー',
  'accountBackup.rollback.scheduled':
    '{bundleName} の復元前データへ戻す準備ができました。甲ブラウザを再起動します...',
  'accountBackup.redo.button': '元に戻す前のデータを再適用',
  'accountBackup.redo.available':
    '再適用できるデータが保管されています（作成: {createdAt}、識別子: {bundleName}）。',
  'accountBackup.redo.checkButton': '再適用データを確認',
  'accountBackup.redo.checkFailed': '再適用データを確認できませんでした。もう一度お試しください。',
  'accountBackup.redo.confirmButton': '再適用して再起動',
  'accountBackup.redo.confirmDetail':
    '現在のアカウント記録と設定を、元に戻す直前に使用していた内容へ完全に切り替えます。現在のデータは新しいロールバック用として削除せず保管されます。再起動後の切り替えと検証が完了するまで、甲ブラウザを終了したり保存フォルダを変更したりしないでください。',
  'accountBackup.redo.confirmMessage': '元に戻す前に使用していたアカウントデータを再適用しますか？',
  'accountBackup.redo.confirmTitle': 'アカウントデータを再適用',
  'accountBackup.redo.failed': '再適用を準備できませんでした。現在のデータは変更されていません。',
  'accountBackup.redo.loading': '再適用データを確認しています...',
  'accountBackup.redo.none': '利用できる再適用データはありません。',
  'accountBackup.redo.recoveryFailed':
    '再適用処理の途中状態を安全に回復できませんでした。データを上書きせず停止しています。甲ブラウザを終了し、restore-rollbacks を削除せずに保管してください。',
  'accountBackup.redo.recoveryFailedTitle': 'アカウントデータ再適用エラー',
  'accountBackup.redo.scheduled':
    '{bundleName} のデータを再適用する準備ができました。甲ブラウザを再起動します...',
  'accountBackup.retention':
    '完了した復元前データと統合前データは、それぞれ最大 {days} 日、アカウントごと {generations} 世代、合計 {capacityGiB} GiB を目安に自動整理します。処理中・不完全・未認識のデータと、各アカウントの最新世代は容量整理では削除しません。',
  'accountBackup.warning':
    '作成されるフォルダは暗号化されず、アカウント識別子・プレイ履歴・編成などを含みます。共有や同期用には使わず、本人だけがアクセスできるローカル保存先を選んでください。',
  'about.appLogoAlt': '{appName}ロゴ',
  'about.cache.description': 'ゲーム画面が表示されない場合、キャッシュクリアで改善が期待できます。',
  'about.cache.heading': 'キャッシュ',
  'about.developer.button': '{appName}側開発者ツール表示',
  'about.developer.description': '{appName}側の開発者ツールを表示します。',
  'about.developer.heading': '開発者向け',
  'about.display.heading': '表示',
  'about.display.taihaWarning':
    '大破警告中は、選択した色にかかわらず赤く表示されます。戦闘結果で大破艦を検出した場合はゲーム画面への入力も保護し、Ctrl + クリックで明示的に解除できます。',
  'about.display.titlebarColor': 'タイトルバー色',
  'about.display.titlebarColor.brown': '茶',
  'about.display.titlebarColor.graphite': 'ダークグレー',
  'about.display.titlebarColor.green': '緑（標準）',
  'about.display.titlebarColor.navy': '紺',
  'about.distributionPage': '配布ページ：',
  'about.intake.description': 'ドロップ情報の集計向上のため、情報提供にご協力ください。',
  'about.intake.heading': 'ゲーム情報提供',
  'about.intake.siteDescription': '{brand} - {gameName}ドロップ情報集計サイト',
  'about.intake.siteLogoAlt': '{brand}ロゴ',
  'about.intake.toggle': 'ドロップ情報を提供する',
  'about.license.button': 'ライセンス...',
  'about.license.description': '同梱しているライブラリのライセンスを表示します。',
  'about.license.dialogTitle': '使用コンポーネントとライセンス',
  'about.license.heading': 'ライセンス',
  'about.license.table.library': 'ライブラリ',
  'about.license.table.license': 'ライセンス',
  'about.license.table.version': 'バージョン',
  'about.records.description':
    '任務・戦果・ドロップなどの記録データは、この端末のデータ保存先に保管されます。',
  'about.records.heading': '記録データ',
  'about.records.syncWarning':
    'PC 間の記録データの自動統合には対応していません。複数の PC から同じ保存先を同時に使ったり、{appName}の起動中に双方向同期したりしないでください。バックアップやコピーは{appName}を終了してから行ってください。',
  'about.rights': 'ゲーム関連画像の権利は各権利者に帰属します。',
  'about.tagline': '艦隊運用支援',
  'about.version': 'ver {version}',
  'battleEquipment.tab.score': '戦果',
  'battleEquipment.tab.history': '戦闘履歴',
  'battleEquipment.tab.ships': '艦船一覧',
  'battleEquipment.tab.slotitems': '装備一覧',
  'battleEquipment.tab.items': 'アイテム一覧',
  'battleEquipment.battle.airSearch.0': '失敗',
  'battleEquipment.battle.airSearch.1': '成功',
  'battleEquipment.battle.airSearch.2': '大成功',
  'battleEquipment.battle.airState.0': '均衡',
  'battleEquipment.battle.airState.1': '確保',
  'battleEquipment.battle.airState.2': '優勢',
  'battleEquipment.battle.airState.3': '劣勢',
  'battleEquipment.battle.airState.4': '喪失',
  'battleEquipment.battle.airStateLong.0': '制空均衡',
  'battleEquipment.battle.airStateLong.1': '制空権確保',
  'battleEquipment.battle.airStateLong.2': '航空優勢',
  'battleEquipment.battle.airStateLong.3': '航空劣勢',
  'battleEquipment.battle.airStateLong.4': '制空権喪失',
  'battleEquipment.battle.formation.1': '単縦',
  'battleEquipment.battle.formation.2': '複縦',
  'battleEquipment.battle.formation.3': '輪形',
  'battleEquipment.battle.formation.4': '梯形',
  'battleEquipment.battle.formation.5': '単横',
  'battleEquipment.battle.formation.6': '警戒',
  'battleEquipment.battle.formation.11': '第一',
  'battleEquipment.battle.formation.12': '第二',
  'battleEquipment.battle.formation.13': '第三',
  'battleEquipment.battle.formation.14': '第四',
  'battleEquipment.battle.formationLong.1': '単縦陣',
  'battleEquipment.battle.formationLong.2': '複縦陣',
  'battleEquipment.battle.formationLong.3': '輪形陣',
  'battleEquipment.battle.formationLong.4': '梯形陣',
  'battleEquipment.battle.formationLong.5': '単横陣',
  'battleEquipment.battle.formationLong.6': '警戒陣',
  'battleEquipment.battle.formationLong.11': '第一対潜警戒',
  'battleEquipment.battle.formationLong.12': '第二前方警戒',
  'battleEquipment.battle.formationLong.13': '第三輪形陣',
  'battleEquipment.battle.formationLong.14': '第四戦闘隊形',
  'battleEquipment.battle.night': '夜',
  'battleEquipment.battle.tactics.1': '同航戦',
  'battleEquipment.battle.tactics.2': '反航戦',
  'battleEquipment.battle.tactics.3': 'T字有利',
  'battleEquipment.battle.tactics.4': 'T字不利',
  'battleEquipment.airbase.base.1': '第一',
  'battleEquipment.airbase.base.2': '第二',
  'battleEquipment.airbase.base.3': '第三',
  'battleEquipment.airbase.action.wait': '待機',
  'battleEquipment.airbase.action.sortie': '出撃',
  'battleEquipment.airbase.action.defense': '防空',
  'battleEquipment.airbase.action.evacuate': '退避',
  'battleEquipment.airbase.action.rest': '休息',
  'battleEquipment.airbase.rangeShort': '半:{value}',
  'battleEquipment.airbase.airPower': '制空:{value}',
  'battleEquipment.airbase.slotAirPower': '制空: {value}',
  'battleEquipment.airbase.stat.firepower': '火力',
  'battleEquipment.airbase.stat.torpedo': '雷撃',
  'battleEquipment.airbase.stat.bombing': '爆装',
  'battleEquipment.airbase.stat.antiAir': '対空',
  'battleEquipment.airbase.stat.antiSubmarine': '対潜',
  'battleEquipment.airbase.stat.antiBomber': '対爆',
  'battleEquipment.airbase.stat.accuracy': '命中',
  'battleEquipment.airbase.stat.interception': '追撃',
  'battleEquipment.airbase.stat.evasion': '回避',
  'battleEquipment.airbase.stat.sortie': '出撃',
  'battleEquipment.airbase.stat.defense': '防空',
  'battleEquipment.airbase.stat.lineOfSight': '索敵',
  'battleEquipment.airbase.stat.armor': '装甲',
  'battleEquipment.airbase.stat.radius': '半径',
  'battleEquipment.map.airbase.available': '出撃可能 x {count} 飛行隊',
  'battleEquipment.map.airbase.none': 'なし',
  'battleEquipment.map.airbase.label': '{base}航空隊(半径:{radius})',
  'battleEquipment.map.recon': '偵察',
  'battleEquipment.map.coefficient': '係数:{value}',
  'battleEquipment.map.airPower.none': 'なし',
  'battleEquipment.map.gauge.unavailable': 'ゲージ情報が未取得です。出撃画面を開いてください。',
  'battleEquipment.map.gauge.difficulty.1': '丁',
  'battleEquipment.map.gauge.difficulty.2': '丙',
  'battleEquipment.map.gauge.difficulty.3': '乙',
  'battleEquipment.map.gauge.difficulty.4': '甲',
  'battleEquipment.map.gauge.cleared': 'クリア',
  'battleEquipment.map.gauge.clearedWithRank': 'クリア {rank}',
  'battleEquipment.map.gauge.combat': '戦力',
  'battleEquipment.map.gauge.transport': '輸送',
  'battleEquipment.map.gauge.value': '{rank}{name}: {current}/{max}',
  'battleEquipment.map.gauge.valueWithRemaining': '{name}: {current}/{required} 残: {remaining}',
  'battleEquipment.map.gauge.counterCleared': '{current}/{required} クリア',
  'battleEquipment.map.gauge.notCleared': '未クリア',
  'battleEquipment.map.fleet.combined': '連合',
  'battleEquipment.map.los': '索敵値({fleet})：{value}',
  'battleEquipment.map.debug.combinedFleet': '連合艦隊:{value}',
  'battleEquipment.map.debug.combinedAirPower': '連合艦隊制空値:{value}',
  'battleEquipment.map.debug.hasAirbase': 'airbase有: {value}',
  'battleEquipment.enemy.composition': '構成',
  'battleEquipment.enemy.hp': '耐久: {value}',
  'battleEquipment.enemy.evasion': '回避: {value}',
  'battleEquipment.history.area': '海域',
  'battleEquipment.history.areaPlaceholder': '海域を選択',
  'battleEquipment.history.bossReached': 'ボス到達:',
  'battleEquipment.history.clearCondition.line1': '条件',
  'battleEquipment.history.clearCondition.line2': 'クリア',
  'battleEquipment.history.dateRange': '検索対象日',
  'battleEquipment.history.endDate': '終了日',
  'battleEquipment.history.resultCount': '出撃件数:',
  'battleEquipment.history.resultUnit': '{count}件',
  'battleEquipment.history.search': '検索',
  'battleEquipment.history.searchLimit': '検索件数',
  'battleEquipment.history.showCellReports': 'セル状況表示',
  'battleEquipment.history.startDate': '開始日',
  'battleEquipment.history.totalAcquired': '獲得合計:',
  'battleEquipment.history.totalUsed': '消費合計:',
  'battleEquipment.history.unselected': '未選択',
  'battleEquipment.history.column.area': '出撃エリア',
  'battleEquipment.history.column.date': '出撃日時',
  'battleEquipment.history.column.route': 'ルート詳細',
  'battleEquipment.history.column.used': '資源消費量',
  'battleEquipment.shipList.count': '艦船数：{count}',
  'battleEquipment.shipList.filter.battleship': '戦艦級',
  'battleEquipment.shipList.filter.carrier': '航空母艦',
  'battleEquipment.shipList.filter.heavyCruiser': '重巡級',
  'battleEquipment.shipList.filter.lightCruiser': '軽巡級',
  'battleEquipment.shipList.filter.destroyer': '駆逐艦',
  'battleEquipment.shipList.filter.escort': '海防艦',
  'battleEquipment.shipList.filter.submarine': '潜水艦',
  'battleEquipment.shipList.filter.auxiliary': '補助艦艇',
  'battleEquipment.shipList.filter.placeholder': '艦名・装備を入力',
  'battleEquipment.shipList.filter.clear': '条件クリア',
  'battleEquipment.shipList.internalId': '内部ID: {id}',
  'battleEquipment.shipList.sallyArea': '札{area}',
  'battleEquipment.shipList.summary.battleship': '戦:{count}',
  'battleEquipment.shipList.summary.carrier': '空:{count}',
  'battleEquipment.shipList.summary.heavyCruiser': '重:{count}',
  'battleEquipment.shipList.summary.lightCruiser': '軽:{count}',
  'battleEquipment.shipList.summary.destroyer': '駆:{count}',
  'battleEquipment.shipList.summary.escort': '海防:{count}',
  'battleEquipment.shipList.summary.submarine': '潜:{count}',
  'battleEquipment.shipList.summary.auxiliary': '補:{count}',
  'battleEquipment.shipList.summary':
    '戦:{battleship} 空:{carrier} 重:{heavyCruiser} 軽:{lightCruiser} 駆:{destroyer} 海防:{escort} 潜:{submarine} 補:{auxiliary}',
  'battleEquipment.shipList.column.sallyArea': '札',
  'battleEquipment.shipList.column.name': '艦名',
  'battleEquipment.shipList.column.firepower': '火力',
  'battleEquipment.shipList.column.armor': '装甲',
  'battleEquipment.shipList.column.torpedo': '雷装',
  'battleEquipment.shipList.column.evasion': '回避',
  'battleEquipment.shipList.column.antiAir': '対空',
  'battleEquipment.shipList.column.antiSubmarine': '対潜',
  'battleEquipment.shipList.column.lineOfSight': '索敵',
  'battleEquipment.shipList.column.luck': '運',
  'battleEquipment.shipList.column.equipment': '装備',
  'battleEquipment.slotitem.filter.clearTitle': 'フィルタをクリア',
  'battleEquipment.slotitem.filter.checkAll': '全チェック',
  'battleEquipment.slotitem.filter.clear': 'クリア',
  'battleEquipment.slotitem.filter.smallGun': '小口径主砲',
  'battleEquipment.slotitem.filter.smallAaGun': '小口径主砲(高角砲)',
  'battleEquipment.slotitem.filter.mediumGun': '中口径主砲',
  'battleEquipment.slotitem.filter.mediumAaGun': '中口径主砲(高角砲)',
  'battleEquipment.slotitem.filter.largeGun': '大口径主砲',
  'battleEquipment.slotitem.filter.secondaryGun': '副砲',
  'battleEquipment.slotitem.filter.secondaryAaGun': '副砲(高角砲)',
  'battleEquipment.slotitem.filter.torpedo': '魚雷/甲標的/潜水艦魚雷',
  'battleEquipment.slotitem.filter.fighter': '艦上戦闘機',
  'battleEquipment.slotitem.filter.diveBomber': '艦上爆撃機',
  'battleEquipment.slotitem.filter.torpedoBomber': '艦上攻撃機',
  'battleEquipment.slotitem.filter.recAircraft': '艦上偵察機',
  'battleEquipment.slotitem.filter.recSeaplane': '水上偵察機',
  'battleEquipment.slotitem.filter.seaplaneFighter': '水上戦闘機',
  'battleEquipment.slotitem.filter.seaplaneBomber': '水上爆撃機',
  'battleEquipment.slotitem.filter.radar': '電探',
  'battleEquipment.slotitem.filter.aaShell': '対空強化弾',
  'battleEquipment.slotitem.filter.apShell': '対艦強化弾',
  'battleEquipment.slotitem.filter.emergencyRepair': 'ダメコン',
  'battleEquipment.slotitem.filter.aaGun': '機銃',
  'battleEquipment.slotitem.filter.sonar': 'ソナー',
  'battleEquipment.slotitem.filter.depthCharge': '爆雷',
  'battleEquipment.slotitem.filter.engineImp': '機関部強化',
  'battleEquipment.slotitem.filter.landingCraft': '上陸用舟艇',
  'battleEquipment.slotitem.filter.autogyro': 'オートジャイロ',
  'battleEquipment.slotitem.filter.aswAircraft': '対潜哨戒機',
  'battleEquipment.slotitem.filter.bulge': 'バルジ',
  'battleEquipment.slotitem.filter.searchlight': '探照灯',
  'battleEquipment.slotitem.filter.drumcan': 'ドラム缶',
  'battleEquipment.slotitem.filter.repairFacility': '艦艇修理施設',
  'battleEquipment.slotitem.filter.starShell': '照明弾',
  'battleEquipment.slotitem.filter.commandFacility': '司令部施設',
  'battleEquipment.slotitem.filter.aviationPersonnel': '航空要員',
  'battleEquipment.slotitem.filter.aaDirector': '高射装置',
  'battleEquipment.slotitem.filter.antiGroundEquipment': '対地装備',
  'battleEquipment.slotitem.filter.shipPersonnel': '水上艦要員',
  'battleEquipment.slotitem.filter.largeFlyingBoat': '大型飛行艇',
  'battleEquipment.slotitem.filter.combatRation': '戦闘糧食',
  'battleEquipment.slotitem.filter.supplies': '補給物資',
  'battleEquipment.slotitem.filter.landBasedFighter': '陸上戦闘機',
  'battleEquipment.slotitem.filter.landBasedAttackAircraft': '陸上攻撃機',
  'battleEquipment.slotitem.filter.landBasedRecAircraft': '噴式戦闘爆撃機',
  'battleEquipment.slotitem.filter.submarineEquipment': '潜水艦装備',
  'battleEquipment.slotitem.filter.smokeScreen': '発煙装置/防空気球',
  'battleEquipment.slotitem.param.firepower': '火力',
  'battleEquipment.slotitem.param.accuracy': '命中',
  'battleEquipment.slotitem.param.torpedo': '雷装',
  'battleEquipment.slotitem.param.torpedoAccuracy': '雷命',
  'battleEquipment.slotitem.param.bombing': '爆装',
  'battleEquipment.slotitem.param.antiAir': '対空',
  'battleEquipment.slotitem.param.fleetDefense': '艦防',
  'battleEquipment.slotitem.param.weightedAntiAir': '加重',
  'battleEquipment.slotitem.param.antiSubmarine': '対潜',
  'battleEquipment.slotitem.param.antiSubmarineAccuracy': '対命',
  'battleEquipment.slotitem.param.evasion': '回避',
  'battleEquipment.slotitem.param.torpedoEvasion': '雷回',
  'battleEquipment.slotitem.param.lineOfSight': '索敵',
  'battleEquipment.slotitem.param.armor': '装甲',
  'battleEquipment.slotitem.rangeLabel': '射程',
  'battleEquipment.slotitem.range.1': '短',
  'battleEquipment.slotitem.range.2': '中',
  'battleEquipment.slotitem.range.3': '長',
  'battleEquipment.slotitem.range.4': '超長',
  'battleEquipment.slotitem.range.5': '超長+',
  'battleEquipment.slotitem.rare.0': 'コモン',
  'battleEquipment.slotitem.rare.1': 'レア',
  'battleEquipment.slotitem.rare.2': 'ホロ',
  'battleEquipment.slotitem.rare.3': 'Sホロ',
  'battleEquipment.slotitem.rare.4': 'SSホロ',
  'battleEquipment.slotitem.rare.5': 'SSホロ',
  'battleEquipment.slotitem.rare.6': 'SSホロ+',
  'battleEquipment.slotitem.rare.7': 'SS++',
  'battleEquipment.slotitem.internalId': '内部ID: {id}',
  'battleEquipment.slotitem.deck': '第{number}艦隊',
  'battleEquipment.slotitem.column.name': '装備名',
  'battleEquipment.slotitem.column.rare': 'レア',
  'battleEquipment.slotitem.column.detail': 'アイテム詳細',
  'battleEquipment.slotitem.column.equippedShip': '装備艦',
  'battleEquipment.slotitem.namePlaceholder': '装備名で絞り込み',
  'battleEquipment.slotitem.count': '装備数：{count}',
  'battleEquipment.score.completed': '{date} 済',
  'battleEquipment.score.notCompleted': '未達成',
  'battleEquipment.score.gauge': 'ゲージ {count}/{countMax}',
  'battleEquipment.score.notCleared': '未攻略',
  'battleEquipment.score.flag.eoQuest': 'EO/任務',
  'battleEquipment.score.flag.eo': 'EO',
  'battleEquipment.score.flag.quest': '任務',
  'battleEquipment.score.weekday.0': '日',
  'battleEquipment.score.weekday.1': '月',
  'battleEquipment.score.weekday.2': '火',
  'battleEquipment.score.weekday.3': '水',
  'battleEquipment.score.weekday.4': '木',
  'battleEquipment.score.weekday.5': '金',
  'battleEquipment.score.weekday.6': '土',
  'battleEquipment.score.reward.eo': 'EO攻略報酬',
  'battleEquipment.score.reward.quarterly': 'クオータリー任務達成報酬',
  'battleEquipment.score.reward.yearly': 'イヤーリー任務達成報酬',
  'battleEquipment.score.reward.quest': '戦果任務達成報酬',
  'battleEquipment.score.questNumber': '任務No.{number}',
  'battleEquipment.score.today': '本日',
  'battleEquipment.score.axis.total': '累計',
  'battleEquipment.score.axis.daily': '当日',
  'battleEquipment.score.series.total': '累計戦果',
  'battleEquipment.score.series.totalForecast': '累計戦果(予測)',
  'battleEquipment.score.series.daily': '当日戦果',
  'battleEquipment.score.series.dailyForecast': '当日戦果(予測)',
  'battleEquipment.score.series.eo': 'EO戦果',
  'battleEquipment.score.series.eoForecast': 'EO戦果(予測)',
  'battleEquipment.score.series.quest': '戦果任務',
  'battleEquipment.score.series.questForecast': '戦果任務(予測)',
  'battleEquipment.score.period.select': '表示年月の選択',
  'battleEquipment.score.period.currentMonth': '今月',
  'battleEquipment.score.tasks.incomplete': '未達成 EO: {eoCount} 戦果任務: {questCount}',
  'battleEquipment.score.tasks.completed': '達成済 EO: {eoCount} 戦果任務: {questCount}',
  'battleEquipment.score.tasks.markAllTemporary': 'すべて仮達成',
  'battleEquipment.score.tasks.clearTemporary': '仮達成クリア',
  'battleEquipment.score.tasks.temporary': '仮達成',
  'battleEquipment.score.inherited': '引継ぎ戦果',
  'battleEquipment.score.forecast': '戦果予測',
  'battleEquipment.score.inherited.help.line1':
    '入力した引継ぎ戦果値を該当月の累計戦果に加算します。',
  'battleEquipment.score.inherited.help.line2':
    'ゲーム上戦果値と一致させたいなどで入力してください。',
  'battleEquipment.score.inherited.help.example': '入力例：',
  'battleEquipment.score.inherited.help.exampleMonth': '当月が4月、',
  'battleEquipment.score.inherited.help.exampleValues':
    'ゲーム上戦果値：350、累積戦果が320、当日戦果が0の場合、4月引継ぎ戦果に30を入力',
  'battleEquipment.score.inherited.month': '{month}月',
  'battleEquipment.score.inherited.save': '保存',
  'battleEquipment.score.inherited.restore': '復元',
  'battleEquipment.score.inherited.clear': 'クリア',
  'battleEquipment.score.inherited.year': '年度: {year}',
  'drop.world.selectEvent': 'イベント海域を選択',
  'drop.cell.select': 'マップ上のセルを選択するとドロップ情報が表示されます',
  'drop.common.noDrop': 'ドロップ無し',
  'drop.common.total': '合計',
  'drop.common.none': 'なし',
  'drop.common.ratio': '割合',
  'drop.column.rarity': 'レア度',
  'drop.column.shipName': '艦名',
  'drop.column.rate': '確率',
  'drop.column.dropCount': 'ドロップ数',
  'drop.column.dropCountTotal': '合計: {count}',
  'drop.column.rankDropCount': 'ランク別ドロップ数',
  'drop.column.winRank': '勝利ランク',
  'drop.byShip.areaColumn': '{shipName} ドロップ海域',
  'drop.filter.rarity': 'レア度',
  'drop.filter.rarity.unique': 'ユニーク',
  'drop.filter.rarity.rare': 'レア',
  'drop.filter.rarity.common': 'コモン',
  'drop.filter.winRank': '勝利ランク',
  'drop.shipCategory.battleship': '戦艦級',
  'drop.shipCategory.carrier': '航空母艦',
  'drop.shipCategory.heavyCruiser': '重巡級',
  'drop.shipCategory.lightCruiser': '軽巡級',
  'drop.shipCategory.destroyer': '駆逐艦',
  'drop.shipCategory.escort': '海防艦',
  'drop.shipCategory.submarine': '潜水艦',
  'drop.shipCategory.auxiliary': '補助艦艇',
  'drop.shipType.noDrop': 'ドロップなし',
  'drop.shipType.unknown': '不明',
  'drop.shipType.battleship': '戦艦級',
  'drop.shipType.carrier': '空母級',
  'drop.shipType.heavyCruiser': '重巡級',
  'drop.shipType.lightCruiser': '軽巡級',
  'drop.shipType.destroyer': '駆逐艦',
  'drop.shipType.escort': '海防艦',
  'drop.shipType.submarine': '潜水艦',
  'drop.shipType.auxiliary': '補助',
  'drop.shipRarity.none': '-',
  'drop.shipRarity.common': 'コモン',
  'drop.shipRarity.rare': 'レア',
  'drop.shipRarity.unique': 'ユニーク',
  'quest.list.summary': '任務情報 遂行中: {active}/{capacity}',
  'quest.list.progress.completed': '達成!',
  'quest.list.progress.label': '達成度: {progress}',
  'quest.list.badge.limited': '限定',
  'quest.list.badge.senka': '戦果{value}',
  'quest.list.formation.ok': '編成:OK',
  'quest.list.formation.ng': '編成:NG',
  'quest.category.formation': '編成',
  'quest.category.sortie': '出撃',
  'quest.category.practice': '演習',
  'quest.category.expedition': '遠征',
  'quest.category.supplyRepair': '補/入',
  'quest.category.factory': '工廠',
  'quest.category.remodel': '改装',
  'quest.type.daily': '日',
  'quest.type.weekly': '週',
  'quest.type.monthly': '月',
  'quest.type.single': '単',
  'quest.type.quarterly': '他',
  'quest.type.yearly': '年',
  'quest.progress.condition': '条件{index}',
  'quest.progress.map.arrival': '{map} 到達',
  'quest.progress.map.victory': '{map} {rank}勝利',
  'quest.progress.map.gauge': '{map} ゲージ破壊',
  'quest.progress.practice.run': '演習実施',
  'quest.progress.practice.victory': '演習 {rank}勝利',
  'quest.progress.repair': '入渠',
  'quest.progress.sortie': '出撃',
  'quest.progress.sortieMap': '{map} 出撃',
  'quest.progress.battle': '戦闘',
  'quest.progress.battleVictory': '戦闘勝利',
  'quest.progress.battle.sVictory': 'S勝利',
  'quest.progress.battle.bossArrival': 'ボス到達',
  'quest.progress.battle.bossVictory': 'ボス勝利',
  'quest.progress.enemy.carrier': '空母系撃沈',
  'quest.progress.enemy.supply': '補給艦撃沈',
  'quest.progress.enemy.submarine': '潜水艦撃沈',
  'quest.progress.enemy.type': '{type}撃沈',
  'quest.progress.enemy.specified': '指定敵艦撃沈',
  'quest.progress.expedition.start': '遠征出発',
  'quest.progress.expedition.success': '遠征成功',
  'quest.progress.expedition.namedSuccess': '{names} 成功',
  'quest.progress.modernization.run': '近代化改修実施',
  'quest.progress.modernization.success': '近代化改修成功',
  'quest.progress.modernization.useShips': '{target}へ{material}{count}隻使用改修成功',
  'quest.progress.supply': '補給',
  'quest.progress.equipment.remodel': '装備改修',
  'quest.progress.equipment.develop': '装備開発',
  'quest.progress.ship.construct': '艦船建造',
  'quest.progress.equipment.discard': '装備廃棄',
  'quest.progress.equipment.namedDiscard': '{name} 廃棄',
  'quest.progress.equipment.proficiencyDiscard': '{name}（熟練度{proficiency}）廃棄',
  'quest.progress.equipment.specifiedDiscard': '指定装備廃棄',
  'quest.progress.equipment.specifiedCondition': '指定装備条件',
  'quest.progress.equipment.flagship': '旗艦装備 {items}',
  'quest.progress.equipment.owned': '{name} 保有',
  'quest.progress.ship.scrap': '艦船解体',
  'quest.progress.fleet.formation': '艦隊編成条件',
  'quest.progress.collection.saury': '秋刀魚所持数',
  'quest.progress.ship.specified': '指定艦',
  'quest.progress.ship.specifiedGirl': '指定艦娘',
  'quest.progress.ship.lightCruiserClass': '軽巡級',
  'quest.progress.ship.heavyCruiserClass': '重巡級',
  'quest.progress.shipType.unknown': '艦種#{type}',
  'quest.progress.shipCategory.unknown': '艦型#{category}',
  'quest.progress.shipType.escort': '海防艦',
  'quest.progress.shipType.destroyer': '駆逐艦',
  'quest.progress.shipType.lightCruiser': '軽巡',
  'quest.progress.shipType.torpedoCruiser': '雷巡',
  'quest.progress.shipType.heavyCruiser': '重巡',
  'quest.progress.shipType.aviationCruiser': '航巡',
  'quest.progress.shipType.lightCarrier': '軽空母',
  'quest.progress.shipType.battleship': '戦艦',
  'quest.progress.shipType.aviationBattleship': '航戦',
  'quest.progress.shipType.carrier': '正規空母',
  'quest.progress.shipType.submarine': '潜水艦',
  'quest.progress.shipType.submarineCarrier': '潜母',
  'quest.progress.shipType.enemySupply': '補給艦',
  'quest.progress.shipType.seaplaneTender': '水母',
  'quest.progress.shipType.landingShip': '揚陸艦',
  'quest.progress.shipType.armoredCarrier': '装母',
  'quest.progress.shipType.repairShip': '工作艦',
  'quest.progress.shipType.submarineTender': '潜水母艦',
  'quest.progress.shipType.trainingCruiser': '練巡',
  'quest.progress.shipType.supplyShip': '補給艦',
  'quest.progress.shipCategory.ayanami': '綾波型',
  'quest.progress.shipCategory.akatsuki': '暁型',
  'quest.progress.shipCategory.fubuki': '吹雪型',
  'quest.progress.shipCategory.sendai': '川内型',
  'quest.progress.shipCategory.yugumo': '夕雲型',
  'quest.progress.shipCategory.akizuki': '秋月型',
  'quest.progress.shipCategory.hiburi': '日振型',
  'quest.progress.shipCategory.ukuru': '鵜来型',
  'quest.progress.equipment.unknown': '装備#{id}',
  'quest.progress.equipment.typeUnknown': '装備種別 {type}',
  'quest.progress.proficiency.max': 'max',
  'quest.progress.proficiency.parenthesized': '（熟練度{value}）',
  'quest.progress.slotitemType.smallMainGun': '小口径主砲',
  'quest.progress.slotitemType.mediumMainGun': '中口径主砲',
  'quest.progress.slotitemType.largeMainGun': '大口径主砲',
  'quest.progress.slotitemType.secondaryGun': '副砲',
  'quest.progress.slotitemType.torpedo': '魚雷',
  'quest.progress.slotitemType.fighter': '艦上戦闘機',
  'quest.progress.slotitemType.diveBomber': '艦上爆撃機',
  'quest.progress.slotitemType.torpedoBomber': '艦上攻撃機',
  'quest.progress.slotitemType.recAircraft': '艦上偵察機',
  'quest.progress.slotitemType.recSeaplane': '水上偵察機',
  'quest.progress.slotitemType.seaplaneBomber': '水上爆撃機',
  'quest.progress.slotitemType.aaGun': '対空機銃',
  'quest.progress.slotitemType.smallRadar': '小型電探',
  'quest.progress.slotitemType.largeRadar': '大型電探',
  'quest.progress.slotitemType.depthCharge': '爆雷',
  'quest.progress.slotitemType.mediumArmor': '中型バルジ',
  'quest.progress.slotitemType.largeArmor': '大型バルジ',
  'quest.progress.slotitemType.engine': '機関部強化',
  'quest.progress.slotitemType.landAttackAircraft': '陸上攻撃機',
  'quest.progress.slotitemType.transport': '輸送用装備',
  'quest.condition.namesMore': '{names} ほか{count}',
  'quest.condition.deckData': '第{deck}艦隊データ',
  'quest.condition.specifiedFleet': '指定艦隊条件',
  'quest.condition.flagshipData': '旗艦データ',
  'quest.condition.flagship': '旗艦 {target}',
  'quest.condition.flagshipLevelAtLeast': '旗艦 {target} Lv{level}以上',
  'quest.condition.flagshipLevelOnlyAtLeast': '旗艦 Lv{level}以上',
  'quest.condition.flagshipLevelRange': '旗艦 Lv{minimum}～{maximum}',
  'quest.condition.flagshipSlot': '旗艦第{slot}スロット {item}',
  'quest.condition.flagshipOtherSlotsEmpty': '旗艦第2スロット以降・補強増設を空にする',
  'quest.condition.countExact': '{label} {count}隻',
  'quest.condition.countRange': '{label} {minimum}～{maximum}隻',
  'quest.condition.countAtLeast': '{label} {count}隻以上',
  'quest.condition.levelAtLeast': '{label} Lv{level}以上',
  'quest.condition.shipCountExact': '編成隻数 {count}隻',
  'quest.condition.shipCountRange': '編成隻数 {minimum}～{maximum}隻',
  'quest.condition.shipCountAtLeast': '編成隻数 {count}隻以上',
  'quest.condition.allowedShipTypes': '編成艦種 {types}のみ',
  'quest.condition.positionShip': '第{position}艦 {target}',
  'quest.condition.positionSlots': '第{position}艦 {slots} {requirement}',
  'quest.condition.slotList': '第{slots}スロット',
  'quest.condition.allFast': '全艦 高速以上',
  'quest.condition.excludingPositions': '指定艦位以外の{target}',
  'quest.condition.excludingShips': '指定艦以外の{target}',
  'quest.condition.deck': '第{deck}艦隊',
  'quest.condition.deckOpen': '{deck}を開放',
  'quest.condition.sortieDeck': '出撃艦隊 {deck}',
  'quest.guide.title': '任務指引',
  'quest.guide.source.live': '現在の「全」任務データ',
  'quest.guide.source.cache': '保存済みの「全」任務キャッシュ',
  'quest.guide.wiki.destination': '攻略Wikiの参照先',
  'quest.guide.wiki.japanese': '日本語Wiki',
  'quest.guide.wiki.chinese': '中文KCWiki',
  'quest.guide.wiki.short.japanese': '日Wiki',
  'quest.guide.wiki.short.chinese': '中Wiki',
  'quest.guide.wiki.open': '開く*',
  'quest.guide.description':
    '任務画面で「全」を開くと候補を更新します。審査済み関係は日Wiki・中文Wikiを照合し、端末内の観測は公式条件と分けて表示します。',
  'quest.guide.summary.candidates': '候補 {count}',
  'quest.guide.summary.claim': '受取 {count}',
  'quest.guide.summary.active': '遂行中 {count}',
  'quest.guide.summary.limited': '期間限定 {count}',
  'quest.guide.summary.limitedCandidate': '限定候補 {count}',
  'quest.guide.summary.recurringUnregistered': '定期関係 未登録 {count}',
  'quest.guide.summary.recurringUnresolved': '定期関係 確認中 {count}',
  'quest.guide.summary.recurringUnregisteredHelp':
    '現在の定期任務のうち、審査済み知識グラフにまだ登録されていない件数です',
  'quest.guide.summary.recurringUnresolvedHelp':
    '現在の定期任務のうち、参照元の不一致または検証中の関係がある件数です',
  'quest.guide.summary.ships': '艦娘 {count}',
  'quest.guide.summary.equipment': '装備 {count}',
  'quest.guide.filter.label': '表示',
  'quest.guide.filter.aria': '任務候補の表示条件',
  'quest.guide.filter.all': 'すべて',
  'quest.guide.filter.current': '受取・遂行中',
  'quest.guide.filter.ready': '準備済み',
  'quest.guide.filter.attention': '要確認・準備',
  'quest.guide.filter.limited': '期間限定',
  'quest.guide.filter.recurringUnregistered': '定期関係 未登録',
  'quest.guide.filter.recurringUnresolved': '定期関係 確認中',
  'quest.guide.filter.recurringReview': '定期関係 要確認',
  'quest.guide.filter.relationReview': '全任務関係 要確認',
  'quest.guide.search.label': '検索',
  'quest.guide.search.aria': '任務番号、名前、説明を検索',
  'quest.guide.search.placeholder': '番号・名前・説明',
  'quest.guide.search.result': '表示 {shown} / {total}',
  'quest.guide.clear': '解除',
  'quest.guide.goal.title': '目標経路',
  'quest.guide.goal.description': '審査済みの任務関係から前提順に表示',
  'quest.guide.goal.searchAria': '目標任務を番号または名前で検索',
  'quest.guide.goal.searchPlaceholder': '目標番号・名前',
  'quest.guide.goal.clearAria': '目標任務の検索を解除',
  'quest.guide.goal.selectAria': '目標任務',
  'quest.guide.goal.select': '目標任務を選択',
  'quest.guide.goal.candidates': '候補 {shown} / {total}',
  'quest.guide.goal.keepSelected': '・選択中を保持',
  'quest.guide.goal.steps': '表示 {shown} / {total}段階',
  'quest.guide.goal.notShown': '状態未確認 {count}件',
  'quest.guide.goal.outsideCurrent': '現在の一覧外 {count}件を省略',
  'quest.guide.goal.viewAria': '目標経路の表示範囲',
  'quest.guide.goal.viewCurrent': '現在の一覧',
  'quest.guide.goal.viewAll': '全経路',
  'quest.guide.goal.preparation': '準備条件 {count}件',
  'quest.guide.goal.missing': '（不足{count}）',
  'quest.guide.goal.expand': '途中 {count}件を表示',
  'quest.guide.goal.collapse': '経路を折りたたむ',
  'quest.guide.goal.preparationTitle': '目標までの装備・アイテム準備',
  'quest.guide.goal.preparationDescription':
    '廃棄可能数はロック中・艦娘装備中・基地航空隊配備中を除外',
  'quest.guide.goal.unknownDescription':
    '「状態未確認」は現在の任務一覧に表示されていない状態です。未達成とは断定せず、完了済み・周期未更新・未開放の可能性を含みます。',
  'quest.guide.goal.conflict':
    '前提情報に不一致または未確認事項があるため、該当箇所以降の経路は自動展開していません。',
  'quest.guide.goal.cycle': '任務関係に循環を検出したため、経路の一部を省略しました。',
  'quest.guide.empty.cache':
    '任務キャッシュがありません。ゲームの任務画面で「全」を一度開いてください。',
  'quest.guide.empty.filter': '表示条件に一致する任務候補がありません。',
  'quest.guide.item.unknown': 'アイテム#{id}',
  'quest.guide.deadline.resetTitle': '更新予定 {date}',
  'quest.guide.deadline.endTitle': '終了予定 {date} / {source}',
  'quest.guide.badge.limited': '期間限定',
  'quest.guide.badge.limitedCandidate': '限定候補',
  'quest.guide.badge.limitedCandidateHelp': '任務名または登録済み番号からの候補判定です',
  'quest.guide.badge.relationUnregistered': '関係未登録',
  'quest.guide.badge.relationUnregisteredHelp':
    '審査済み知識グラフに任務関係がまだ登録されていません。未知の前提任務があるという意味ではありません',
  'quest.guide.badge.relationUnresolved': '関係確認中',
  'quest.guide.badge.relationUnresolvedHelp': '参照元の不一致または検証中の任務関係があります',
  'quest.guide.badge.conditionOk': '条件OK',
  'quest.guide.badge.conditionNg': '条件NG',
  'quest.guide.badge.formationOk': '編成OK',
  'quest.guide.badge.formationNg': '編成NG',
  'quest.guide.badge.equipmentConditions': '装備条件 {count}',
  'quest.guide.badge.itemConditions': 'アイテム条件 {count}',
  'quest.guide.progress.measured': '実測進捗',
  'quest.guide.progress.measuredWithValue': '実測進捗 {value}',
  'quest.guide.knowledge.toggle': '根拠',
  'quest.guide.reward.fuel': '燃 {value}',
  'quest.guide.reward.ammo': '弾 {value}',
  'quest.guide.reward.steel': '鋼 {value}',
  'quest.guide.reward.bauxite': 'ボ {value}',
  'quest.guide.reward.select': '選択報酬 {count}候補',
  'quest.guide.reward.other': 'その他報酬あり',
  'quest.guide.relation.learnedBefore': '推定直前:',
  'quest.guide.relation.learnedAfter': '推定後続:',
  'quest.guide.knowledge.title': '任務知識と根拠',
  'quest.guide.knowledge.description': '審査済み関係のみ構造化・検索リンクは参考',
  'quest.guide.knowledge.limitedEvidence': '期間限定の根拠',
  'quest.guide.knowledge.endPlanned': '終了予定 {date}',
  'quest.guide.knowledge.endUnknown': '終了時刻は未確認',
  'quest.guide.knowledge.usedEvidence': '判定に利用中',
  'quest.guide.knowledge.curatedRelations': '審査済みの任務関係',
  'quest.guide.knowledge.curatedEmpty':
    '審査済み知識グラフに登録済みですが、表示できる前提・後続関係はありません。',
  'quest.guide.knowledge.unregistered':
    '審査済みの任務関係は未登録です。未知の前提任務があるという意味ではありません。',
  'quest.guide.knowledge.prerequisite': '前提',
  'quest.guide.knowledge.verified': '確認済',
  'quest.guide.knowledge.sourceCount': '{count}件の参照元 / {date}確認',
  'quest.guide.knowledge.downstream': '後続',
  'quest.guide.knowledge.prerequisiteCondition': '前提条件: {mode}',
  'quest.guide.knowledge.verifiedAt': '{date}確認',
  'quest.guide.knowledge.fleetConditions': '現在の編成条件',
  'quest.guide.knowledge.fleetConditionsHelp':
    '対象艦隊の艦種・隻数・レベルを端末内で照合しています。',
  'quest.guide.knowledge.executionConditions': '現在の実行条件',
  'quest.guide.knowledge.executionConditionsHelp':
    '第1艦隊・旗艦・装備の現在値を端末内で照合しています。',
  'quest.guide.condition.satisfied': '満たす',
  'quest.guide.condition.unmet': '未達',
  'quest.guide.condition.unknown': '未取得',
  'quest.guide.preparation.equipment': '装備準備',
  'quest.guide.preparation.equipmentHelp':
    '廃棄可能数はロック中・装備中・基地航空隊配備中を除外しています。',
  'quest.guide.preparation.items': 'アイテム準備',
  'quest.guide.preparation.itemsHelp': '現在取得済みの保有アイテム数と必要所持数を比較しています。',
  'quest.guide.preparation.owned': '所持',
  'quest.guide.preparation.missing': '不足 {count}',
  'quest.guide.preparation.ready': '準備済み',
  'quest.guide.knowledge.observedRelations': '端末内で観測した任務関係',
  'quest.guide.knowledge.observedEmpty': 'まだ関係を観測していません。',
  'quest.guide.knowledge.observedBefore': '推定直前',
  'quest.guide.knowledge.observedAfter': '推定後続',
  'quest.guide.pagination.aria': '任務指引のページ',
  'quest.guide.pagination.previous': '前へ',
  'quest.guide.pagination.next': '次へ',
  'quest.guide.confidence.verified': '取得済',
  'quest.guide.confidence.supported': '参考確認',
  'quest.guide.confidence.observed': '観測',
  'quest.guide.prerequisite.all': 'すべて必要',
  'quest.guide.prerequisite.any': 'いずれか必要',
  'quest.guide.conflict.underReview': 'この参照元では、記載された前提条件を検証中です。',
  'quest.guide.conflict.incomplete': 'この参照元には、未特定の追加前提条件も記載されています。',
  'quest.guide.conflict.disagreement': '参照元の不一致',
  'quest.guide.conflict.pending': '前提情報を確認中',
  'quest.guide.conflict.disagreementSummary':
    '参照元によって前提任務の記述が一致しないため、自動判定には使用しません。',
  'quest.guide.conflict.pendingSummary':
    '前提任務の記述が検証中または不完全なため、自動判定には使用しません。',
  'quest.guide.source.japaneseWiki': '日本語攻略Wiki',
  'quest.guide.source.chineseWiki': '中文KCWiki',
  'quest.guide.goal.status.claim': '報酬受取',
  'quest.guide.goal.status.active': '遂行中',
  'quest.guide.goal.status.available': '表示中',
  'quest.guide.goal.status.notShown': '状態未確認',
  'quest.guide.equipmentKind.hold': '保有',
  'quest.guide.equipmentKind.discard': '廃棄',
  'quest.guide.equipmentKind.equip': '旗艦装備',
  'quest.guide.cadence.yearlyMonth': '年{month}月',
  'quest.guide.cadence.daily': 'デイリー',
  'quest.guide.cadence.weekly': 'ウィークリー',
  'quest.guide.cadence.monthly': 'マンスリー',
  'quest.guide.cadence.single': '単発',
  'quest.guide.cadence.quarterly': 'クォータリー',
  'quest.guide.cadence.unknown': '周期不明',
  'quest.guide.deadline.resetHours': '更新まで約{count}時間',
  'quest.guide.deadline.resetDays': '更新まで約{count}日',
  'quest.guide.deadline.endPassed': '終了予定を経過',
  'quest.guide.deadline.endHours': '終了まで約{count}時間',
  'quest.guide.deadline.endDays': '終了まで約{count}日',
  'quest.guide.slotPressure.unknown': '遂行中 {active} / 上限未取得',
  'quest.guide.slotPressure.full': '受諾枠 {active}/{capacity}（空きなし）',
  'quest.guide.slotPressure.available': '受諾枠 {active}/{capacity}（空き{remaining}）',
  'quest.guide.evidence.gameList': '現在のゲーム任務一覧',
  'quest.guide.evidence.cachedList': '保存済み任務キャッシュ',
  'quest.guide.evidence.explicitLimited': '任務名に期間限定であることが明記されています',
  'quest.guide.equipment.any': '任意の装備',
  'quest.guide.equipment.level': '{name} ★+{level}',
  'quest.guide.equipment.proficiency': '{name}（熟練度{level}）',
  'quest.guide.knowledge.type.practice': '演習',
  'quest.guide.knowledge.type.practiceDeck': '編成条件付き演習',
  'quest.guide.knowledge.type.repair': '入渠',
  'quest.guide.knowledge.type.collectItem': 'アイテム収集',
  'quest.guide.knowledge.type.collectItemCondition': '条件付きアイテム収集',
  'quest.guide.knowledge.type.mapStart': '指定海域への出撃',
  'quest.guide.knowledge.type.mapStartDeck': '編成条件付き出撃',
  'quest.guide.knowledge.type.battle': '戦闘',
  'quest.guide.knowledge.type.battleEnemy': '指定敵との戦闘',
  'quest.guide.knowledge.type.battleSpecial': '特定戦闘',
  'quest.guide.knowledge.type.battleMap': '指定海域での戦闘',
  'quest.guide.knowledge.type.battleMapDeck': '編成条件付き海域戦闘',
  'quest.guide.knowledge.type.mapGoal': '指定海域の到達',
  'quest.guide.knowledge.type.gauge': '海域ゲージ攻略',
  'quest.guide.knowledge.type.expeditionStart': '遠征開始',
  'quest.guide.knowledge.type.expedition': '遠征',
  'quest.guide.knowledge.type.expeditionSpecific': '指定遠征',
  'quest.guide.knowledge.type.modernization': '近代化改修',
  'quest.guide.knowledge.type.modernizationShipType': '艦種指定の近代化改修',
  'quest.guide.knowledge.type.modernizationShip': '艦娘指定の近代化改修',
  'quest.guide.knowledge.type.modernizationTargetMaterial': '艦娘指定の改修先・素材',
  'quest.guide.knowledge.type.modernizationMaterialType': '艦種指定の改修素材',
  'quest.guide.knowledge.type.modernizationCategory': '艦種カテゴリ指定の近代化改修',
  'quest.guide.knowledge.type.modernizationCategoryType': '艦種カテゴリ・艦種指定の近代化改修',
  'quest.guide.knowledge.type.supply': '補給',
  'quest.guide.knowledge.type.remodel': '改修工廠',
  'quest.guide.knowledge.type.develop': '装備開発',
  'quest.guide.knowledge.type.discard': '装備廃棄',
  'quest.guide.knowledge.type.discardSpecified': '装備指定の廃棄',
  'quest.guide.knowledge.type.construct': '建造',
  'quest.guide.knowledge.type.scrap': '解体',
  'quest.guide.knowledge.type.formation': '編成',
  'quest.guide.knowledge.type.equipmentCondition': '装備条件',
  'quest.guide.knowledge.definition.unit': '達成単位 {units}',
  'quest.guide.knowledge.definition.maps': '対象海域 {maps}',
  'quest.guide.knowledge.definition.condition': '編成・装備条件の判定あり',
  'quest.guide.evidence.localObservation': '端末内の観測',
  'quest.guide.evidence.localObservationSummary':
    '同時変化を {count}回観測（公式条件ではありません）',
  'quest.guide.evidence.liveData': '現在のゲームデータ',
  'quest.guide.evidence.cachedData': '保存済みの任務キャッシュ',
  'quest.guide.evidence.liveDataSummary': '任務名・説明・状態・基本報酬を現在の任務一覧から取得',
  'quest.guide.evidence.cachedDataSummary':
    '以前取得した任務名・説明・状態・基本報酬（現在と異なる可能性あり）',
  'quest.guide.evidence.bundledDefinition': 'アプリ内蔵定義',
  'quest.guide.evidence.curated': '審査済み攻略情報',
  'quest.guide.evidence.curatedConflict': '参照元 {count}件に不一致あり（自動判定から除外）',
  'quest.guide.evidence.curatedVerified': '参照元 {count}件で任務関係を照合済み',
  'quest.guide.reference.japaneseSearch': '日本語Wiki検索',
  'quest.guide.reference.chineseSearch': '中文KCWiki検索',
  'quest.guide.status.claim': '報酬受取',
  'quest.guide.status.active': '遂行中',
  'quest.guide.status.available': '受諾可能',
  'quest.guide.readiness.invalid': '現在無効',
  'quest.guide.readiness.invalidDetail': 'ゲームデータで現在無効な任務として通知されています',
  'quest.guide.readiness.claim': '受取可能',
  'quest.guide.readiness.claimDetail': '報酬を受け取れる状態です',
  'quest.guide.readiness.mapBlocked': '海域未開放',
  'quest.guide.readiness.mapBlockedDetail': '対象海域が現在のローカル海域データでは未開放です',
  'quest.guide.readiness.preparation': '要準備',
  'quest.guide.readiness.preparationDetail':
    '現在のローカル確認で未達の準備条件が{count}件あります',
  'quest.guide.readiness.unknown': '要確認',
  'quest.guide.readiness.unknownDetail': '現在のローカルデータだけでは判定できない条件があります',
  'quest.guide.readiness.ready': '準備OK',
  'quest.guide.readiness.readyDetail': '現在確認できるローカル実行条件を満たしています',
  'quest.guide.readiness.noLocalCheck': 'この任務には現在ローカルで判定できる実行条件がありません',
  'quest.guide.reason.claim': '今すぐ報酬を受け取れます',
  'quest.guide.reason.progress': '現在の進捗 {progress}%',
  'quest.guide.reason.available': '現在の任務一覧に出現しています',
  'quest.guide.reason.limitedVerified': '期間限定（{source}で確認）',
  'quest.guide.reason.limitedCandidate': '期間限定の可能性が高いため優先',
  'quest.guide.caution.endUnknown': '終了時刻は確認できていません',
  'quest.guide.reason.deadlineEnd': '{deadline}：終了前に確認',
  'quest.guide.reason.deadlineReset': '{deadline}：失効前に確認',
  'quest.guide.reason.equipmentReady': '装備準備OK {count}条件',
  'quest.guide.caution.equipmentMissing': '装備準備不足 合計{count}',
  'quest.guide.reason.itemsReady': 'アイテム準備OK {count}条件',
  'quest.guide.caution.itemsMissing': 'アイテム準備不足 合計{count}',
  'quest.guide.reason.single': '単発任務：後続任務の入口候補',
  'quest.guide.reason.selectReward': '選択報酬 {count}候補',
  'quest.guide.reason.otherReward': '資源以外の報酬あり',
  'quest.guide.reason.materials': '基本資源 合計{count}',
  'quest.guide.reason.senka': '戦果 +{value}',
  'quest.guide.reason.fleetChecksReady': '現在の編成条件 {count}件を満たしています',
  'quest.guide.caution.fleetChecksMissing': '現在の編成条件 未達{failed}/{total}',
  'quest.guide.reason.fleetMatch': '現在の第1艦隊が条件一致',
  'quest.guide.caution.fleetMismatch': '現在の第1艦隊は条件不一致',
  'quest.guide.reason.executionChecksReady': '現在の実行条件 {count}件を満たしています',
  'quest.guide.caution.executionChecksMissing': '現在の実行条件 未達{failed}/{total}',
  'quest.guide.caution.executionMismatch': '現在の実行条件は未達です',
  'quest.guide.reason.maps': '対象海域 {maps}',
  'quest.guide.caution.mapsBlocked': '未開放の可能性がある海域: {maps}',
  'quest.guide.reason.learnedBefore': 'ローカル観測の直前任務 {count}件',
  'quest.guide.reason.learnedAfter': 'ローカル観測の後続任務 {count}件',
  'quest.guide.reason.curatedBefore': '審査済み前提 {count}件',
  'quest.guide.reason.curatedAfter': '審査済み後続 {count}件',
  'quest.guide.caution.curatedConflict': '攻略情報の参照元に不一致あり',
  'quest.guide.caution.invalid': '現在無効な任務として通知されています',
  'common.error': 'エラー',
  'common.loading': '読み込み中...',
  'common.retry': '再試行',
  'common.browse': '参照',
  'common.clear': 'クリア',
  'common.close': '閉じる',
  'common.minimize': '最小化',
  'common.noData': '表示するデータがありません。',
  'common.ok': 'OK',
  'common.resetDefault': '既定値に戻す',
  'cache.clear': 'ブラウザのキャッシュをクリア',
  'cache.cleared': 'キャッシュをクリアしました',
  'cache.clearing': 'キャッシュをクリア中...',
  'cache.clearFailed': 'キャッシュのクリアに失敗しました。もう一度お試しください。',
  'capture.folder.open': 'スクリーンショット・録画フォルダを開く',
  'capture.recording.prepare': '録画を準備しています',
  'capture.recording.start': '録画を開始',
  'capture.recording.startedGame': 'ゲーム画面の録画を開始しました',
  'capture.recording.startedWindow': '甲ブラウザ画面全体の録画を開始しました',
  'capture.recording.startFailed': '録画を開始できませんでした',
  'capture.recording.stop': '録画を停止',
  'capture.recording.stopping': '録画を停止し、保存しています',
  'capture.screenshot': 'スクリーンショット',
  'capture.screenshotFailed': 'スクリーンショットの保存に失敗しました',
  'capture.screenshotSaved': '保存しました: {fileName}',
  'capture.screenshotUnavailable': 'スクリーンショットを取得できませんでした',
  'dataFolder.open': 'データ保存先を開く',
  'dataFolder.opened': 'データ保存先を開きました',
  'dataFolder.opening': 'データ保存先を開いています...',
  'dataFolder.openFailed': 'データ保存先を開けませんでした。もう一度お試しください。',
  'file.saved': '{fileName} を保存しました',
  'main.menu.file': 'ファイル',
  'main.menu.close': '閉じる',
  'main.menu.view': '表示',
  'main.menu.reload': 'リロード',
  'main.menu.forceReload': 'キャッシュを無視してリロード',
  'main.menu.back': '戻る',
  'main.menu.forward': '進む',
  'main.menu.devtools': '開発者ツール',
  'main.recording.errorTitle': 'レコーディング失敗',
  'main.recording.writeFailed': 'ファイル書き込みに失敗しました',
  'main.csv.dialogTitle': '艦船一覧を CSV で保存',
  'main.csv.openFailedTitle': '保存に失敗しました',
  'main.csv.writeFailedTitle': '書き込みに失敗しました',
  'main.csv.pathUnavailable': 'パスがありません',
  'navigation.panel.about.line1': 'アプリ',
  'navigation.panel.about.line2': '情報',
  'navigation.panel.battletab.line1': '戦果',
  'navigation.panel.battletab.line2': '戦闘履歴',
  'navigation.panel.chart.line1': '資源',
  'navigation.panel.chart.line2': '記録',
  'navigation.panel.deckport.line1': '編成',
  'navigation.panel.dockquestlist.line1': '任務',
  'navigation.panel.dockquestlist.line2': 'ドック',
  'navigation.panel.dropbymap.line1': 'ドロップ履歴',
  'navigation.panel.dropbymap.subtitle': '（マップ別）',
  'navigation.panel.dropbyship.line1': 'ドロップ履歴',
  'navigation.panel.dropbyship.subtitle': '（艦名別）',
  'navigation.panel.missioncheck.line1': '遠征',
  'navigation.panel.missioncheck.line2': 'チェック',
  'navigation.panel.questguide.line1': '任務',
  'navigation.panel.questguide.line2': '指引',
  'navigation.panel.shipitems.line1': '艦隊/装備',
  'navigation.panel.shipitems.line2': 'アイテム',
  'navigation.page.drops': 'ドロップ',
  'navigation.page.operations': '運用',
  'navigation.page.overview': '任務指引',
  'navigation.page.records': '戦闘・装備',
  'navigation.page.status': 'ドック・任務',
  'navigation.page.tasks': '任務',
  'option.category.extension': '拡張機能',
  'option.category.extensionDescription': '拡張機能に関する設定',
  'option.category.general': '一般',
  'option.category.generalDescription': '基本的な動作に関する設定',
  'option.category.network': '通信設定',
  'option.category.networkDescription': 'プロキシや通信動作に関する設定',
  'option.categoryLabel': '設定カテゴリ',
  'option.captureFolder.ariaLabel': 'スクリーンショットと録画の保存先フォルダ',
  'option.captureFolder.description': 'スクリーンショットと録画の保存先フォルダを指定します。',
  'option.captureFolder.dialogTitle': 'キャプチャ保存先フォルダを選択',
  'option.captureFolder.placeholder': '保存先フォルダを選択',
  'option.captureFolder.title': 'スクリーンショット・録画保存フォルダ',
  'option.defaultValueLabel': '既定値:',
  'option.extension.description':
    '読み込むパッケージ化されていない拡張機能のフォルダを指定します。変更は甲ブラウザ再起動後に反映されます。',
  'option.extension.dialogTitle': '読み込む拡張機能フォルダを選択',
  'option.extension.folderAriaLabel': '読み込む拡張機能フォルダ',
  'option.extension.folderPlaceholder': '拡張機能フォルダを選択',
  'option.extension.folderTitle': '拡張機能フォルダ',
  'option.extension.security':
    '信頼できる拡張機能のみを指定してください。拡張機能によってはWeb表示や通信内容を監視・変更できる可能性があるため、ゲーム通信へ影響する拡張機能は使用しないでください。',
  'option.extension.section': '読み込み設定',
  'option.loadError.message':
    '設定情報の取得中にエラーが発生しました。設定画面を閉じてから、もう一度開いてください。',
  'option.loadError.title': '設定を読み込めませんでした',
  'option.network.proxy.autoDetect': '自動検出',
  'option.network.proxy.description':
    'アプリ内通信に使用するプロキシ設定を指定します。変更は甲ブラウザ再起動後に反映されます。',
  'option.network.proxy.direct': 'プロキシを使用しない',
  'option.network.proxy.externalToolDescription':
    '{tool} などの Proxy 型ツールを使う場合は、そのツールの待受アドレスを固定プロキシに指定します。甲ブラウザと外部ツールの両方が同じゲーム通信を観測できます。この設定で甲ブラウザ自体がプロキシサーバーになることはありません。',
  'option.network.proxy.fixedAriaLabel': '固定プロキシサーバー',
  'option.network.proxy.fixedClearAriaLabel': '固定プロキシサーバーをクリア',
  'option.network.proxy.fixedExampleLabel': '設定例:',
  'option.network.proxy.fixedPlaceholder': '例: http=localhost:40620;https=localhost:40620',
  'option.network.proxy.fixedTitle': '固定プロキシサーバーを使用',
  'option.network.proxy.pacAriaLabel': 'PAC スクリプト URL',
  'option.network.proxy.pacClearAriaLabel': 'PAC スクリプト URL をクリア',
  'option.network.proxy.pacDataExampleLabel': '設定例(data):',
  'option.network.proxy.pacHttpExampleLabel': '設定例(http):',
  'option.network.proxy.pacPlaceholder': '例: http://localhost:8080/proxy.pac',
  'option.network.proxy.pacProtocols':
    'サポートプロトコル: {supported} 未サポートプロトコル: {unsupported}',
  'option.network.proxy.pacTitle': 'PAC スクリプトを使用',
  'option.network.proxy.section': 'プロキシ設定',
  'option.network.proxy.system': 'システム設定を使用 (規定値)',
  'option.network.proxy.title': 'プロキシの使用方法',
  'option.recording.description': 'タイトルバーの録画ボタンで保存する画面を選択します。',
  'option.recording.gameDescription': 'ゲームの映像と音声を1200×720で録画します。',
  'option.recording.gameTitle': 'ゲーム画面のみ',
  'option.recording.section': '録画',
  'option.recording.targetTitle': '録画範囲',
  'option.recording.windowDescription':
    'ゲーム、タイトルバー、表示中のアシストをまとめて録画します。',
  'option.recording.windowTitle': '甲ブラウザ画面全体',
  'option.savePath.section': '保存パス',
  'option.title': '甲ブラウザ 設定',
  'operation.common.total': '合計',
  'operation.dock.construction.title': '建造ドック',
  'operation.dock.construction.progress': '建造',
  'operation.dock.repair.title': '入渠ドック',
  'operation.dock.repair.progress': '修復',
  'operation.dock.completed': '完了',
  'operation.dock.largeConstruction': '大型建造:',
  'operation.dock.remaining': '残り:',
  'operation.dock.empty': 'Empty',
  'operation.deck.antiAirCutIn.none': '対空CIなし',
  'operation.deck.antiAirCutIn.failure': '不発: {rate}%',
  'operation.deck.antiAirCutIn.rate': '{rate}%',
  'operation.deck.antiAirCutIn.typeRate': '{type}種: {rate}%',
  'operation.deck.antiAirCutIn.types': '{types}種 対空CI',
  'operation.deck.antiAirCutIn.total': '対空CI合計: {rate}',
  'operation.deck.antiAirCutIn.fleetDefense': '艦防: {value}',
  'operation.deck.antiAirCutIn.fixedVariable': '固定:{fixed} 変動:{variable}',
  'operation.deck.cutIn.aa.0': 'FBA',
  'operation.deck.cutIn.aa.1': 'BBA',
  'operation.deck.cutIn.aa.2': 'BA',
  'operation.deck.cutIn.fa.0': '主主',
  'operation.deck.cutIn.fa.1': '主徹',
  'operation.deck.cutIn.fa.2': '主電',
  'operation.deck.cutIn.fa.3': '主副',
  'operation.deck.cutIn.fa.4': '連撃',
  'operation.deck.cutIn.fa.5': '海空',
  'operation.deck.cutIn.fa.6': '瑞立',
  'operation.deck.cutIn.night.0.long': '夜連撃',
  'operation.deck.cutIn.night.0.short': '連撃',
  'operation.deck.cutIn.night.1.long': '主主(2.0)',
  'operation.deck.cutIn.night.1.short': '主主',
  'operation.deck.cutIn.night.2.long': '主副(1.75)',
  'operation.deck.cutIn.night.2.short': '主副',
  'operation.deck.cutIn.night.3.long': '魚雷(1.5)',
  'operation.deck.cutIn.night.3.short': '魚雷',
  'operation.deck.cutIn.night.4.long': '主魚(1.3)',
  'operation.deck.cutIn.night.4.short': '主魚',
  'operation.deck.cutIn.night.20.long': '主魚電(1.3)',
  'operation.deck.cutIn.night.20.short': '主魚電弱',
  'operation.deck.cutIn.night.21.long': '主魚電(2.0)',
  'operation.deck.cutIn.night.21.short': '主魚電強+',
  'operation.deck.cutIn.night.22.long': '主魚電(1.9)',
  'operation.deck.cutIn.night.22.short': '主魚電強+',
  'operation.deck.cutIn.night.23.long': '主魚電(1.8)',
  'operation.deck.cutIn.night.23.short': '主魚電強+',
  'operation.deck.cutIn.night.24.long': '主魚電(1.7)',
  'operation.deck.cutIn.night.24.short': '主魚電強',
  'operation.deck.cutIn.night.25.long': '主魚電(1.6)',
  'operation.deck.cutIn.night.25.short': '主魚電強',
  'operation.deck.cutIn.night.30.long': '魚見電(1.2)',
  'operation.deck.cutIn.night.30.short': '魚見電弱',
  'operation.deck.cutIn.night.31.long': '魚見電(1.84)',
  'operation.deck.cutIn.night.31.short': '魚見電強+',
  'operation.deck.cutIn.night.32.long': '魚見電(1.76)',
  'operation.deck.cutIn.night.32.short': '魚見電強+',
  'operation.deck.cutIn.night.33.long': '魚見電(1.68)',
  'operation.deck.cutIn.night.33.short': '魚見電強+',
  'operation.deck.cutIn.night.34.long': '魚見電(1.57)',
  'operation.deck.cutIn.night.34.short': '魚見電強',
  'operation.deck.cutIn.night.35.long': '魚見電(1.5)',
  'operation.deck.cutIn.night.35.short': '魚見電強',
  'operation.deck.cutIn.night.40.long': '魚水魚(1.5)',
  'operation.deck.cutIn.night.40.short': '魚水魚',
  'operation.deck.cutIn.night.41.long': 'ド水魚(1.3)',
  'operation.deck.cutIn.night.41.short': 'ド水魚',
  'operation.deck.cutIn.night.50.long': '夜瑞(1.24)',
  'operation.deck.cutIn.night.50.short': '夜瑞',
  'operation.deck.cutIn.night.51.long': '夜瑞電(1.28)',
  'operation.deck.cutIn.night.51.short': '夜瑞電',
  'operation.deck.cutIn.night.52.long': '夜瑞2(1.32)',
  'operation.deck.cutIn.night.52.short': '夜瑞2',
  'operation.deck.cutIn.night.53.long': '夜瑞2電(1.36)',
  'operation.deck.cutIn.night.53.short': '夜瑞2電',
  'operation.deck.cutIn.night.100.long': '潜魚電(1.75)',
  'operation.deck.cutIn.night.100.short': '潜魚電',
  'operation.deck.cutIn.night.101.long': '潜魚(1.6)',
  'operation.deck.cutIn.night.101.short': '潜魚',
  'operation.deck.cutIn.nightAir.0.long': '夜攻',
  'operation.deck.cutIn.nightAir.0.short': '夜攻',
  'operation.deck.cutIn.nightAir.1.long': '戦戦攻(1.25)',
  'operation.deck.cutIn.nightAir.1.short': '戦戦攻',
  'operation.deck.cutIn.nightAir.2.long': '戦攻(1.2)',
  'operation.deck.cutIn.nightAir.2.short': '戦攻',
  'operation.deck.cutIn.nightAir.3.long': '戦彗(1.2)',
  'operation.deck.cutIn.nightAir.3.short': '戦彗',
  'operation.deck.cutIn.nightAir.4.long': '攻彗(1.2)',
  'operation.deck.cutIn.nightAir.4.short': '攻彗',
  'operation.deck.cutIn.nightAir.5.long': '戦爆(1.2)',
  'operation.deck.cutIn.nightAir.5.short': '戦爆',
  'operation.deck.cutIn.nightAir.6.long': '攻爆(1.2)',
  'operation.deck.cutIn.nightAir.6.short': '攻爆',
  'operation.deck.cutIn.nightAir.7.long': '爆彗(1.2)',
  'operation.deck.cutIn.nightAir.7.short': '爆彗',
  'operation.deck.cutIn.nightAir.8.long': '戦他他(1.18)',
  'operation.deck.cutIn.nightAir.8.short': '戦他他',
  'operation.deck.deckName.1': '第一艦隊',
  'operation.deck.deckName.2': '第二艦隊',
  'operation.deck.deckName.3': '第三艦隊',
  'operation.deck.deckName.4': '第四艦隊',
  'operation.deck.escape': '退避',
  'operation.deck.noAirControlEquipment': '艦隊に制空戦装備なし',
  'operation.deck.range.1': '短',
  'operation.deck.range.2': '中',
  'operation.deck.range.3': '長',
  'operation.deck.range.4': '超長',
  'operation.deck.range.5': '超長+',
  'operation.deck.section.antiAirCutIn': '対空 / カットイン',
  'operation.deck.section.carrierCutIn': '空母 / カットイン',
  'operation.deck.section.dayObservation': '弾着 / 観測射撃',
  'operation.deck.section.nightAirCutIn': '夜襲 / カットイン',
  'operation.deck.section.nightCutIn': '夜戦 / カットイン',
  'operation.deck.section.other': 'その他',
  'operation.deck.section.specialAttack': '特殊砲撃',
  'operation.deck.senseiTaisen.0': '先制対潜',
  'operation.deck.senseiTaisen.1': '自動対潜',
  'operation.deck.specialAttack': '特殊砲撃',
  'operation.deck.specialAttack.night': '夜戦突撃',
  'operation.deck.speed.1': '低速',
  'operation.deck.speed.2': '高速',
  'operation.deck.speed.3': '高速+',
  'operation.deck.speed.4': '最速',
  'operation.deck.stat.aircraft': '搭載',
  'operation.deck.stat.antiAir': '対空',
  'operation.deck.stat.antiSubmarine': '対潜',
  'operation.deck.stat.armor': '装甲',
  'operation.deck.stat.ammunition': '弾薬',
  'operation.deck.stat.condition': 'コンディション',
  'operation.deck.stat.evasion': '回避',
  'operation.deck.stat.evasionRate': '回避率',
  'operation.deck.stat.evasionTerm': '回避項',
  'operation.deck.stat.firepower': '火力',
  'operation.deck.stat.fleetAntiAir': '艦隊防空',
  'operation.deck.stat.fuel': '燃料',
  'operation.deck.stat.hitRate': '命中率',
  'operation.deck.stat.hitTerm': '命中項',
  'operation.deck.stat.hp': '耐久',
  'operation.deck.stat.luck': '運',
  'operation.deck.stat.nextLevel': '次のレベルまで',
  'operation.deck.stat.range': '射程',
  'operation.deck.stat.search': '索敵',
  'operation.deck.stat.shootdown': '撃墜 割合/固定',
  'operation.deck.stat.speed': '速力',
  'operation.deck.stat.torpedo': '雷装',
  'operation.deck.stat.weightedAntiAir': '加重対空',
  'operation.deck.tag.antiAirRocket': '噴弾',
  'operation.deck.tag.nightScout': '夜偵',
  'operation.deck.tag.openingTorpedo': '先制雷撃',
  'operation.deckPort.airControl': '制空値',
  'operation.deckPort.transport': '輸送',
  'operation.deckPort.transportValue': '輸送値',
  'operation.mission.badge.completed': '完了',
  'operation.mission.badge.returning': '帰還中',
  'operation.mission.badge.running': '遠征中',
  'operation.mission.filter.back': '遠征一覧に戻る',
  'operation.mission.filter.conditions': '絞り込み条件',
  'operation.mission.filter.hideCleared': 'クリア済非表示',
  'operation.mission.filter.monthly': 'マンスリー',
  'operation.mission.filter.show': '表示',
  'operation.mission.fleet.2': '第二艦隊',
  'operation.mission.fleet.3': '第三艦隊',
  'operation.mission.fleet.4': '第四艦隊',
  'operation.mission.keep': '常に表示する',
  'operation.mission.rewardBonus': '報酬+{percent}%',
  'operation.mission.result.failed': '失敗',
  'operation.mission.result.succeeded': '成功',
  'operation.mission.result.succeeded2': '大成功',
  'operation.mission.reward.confirmed': '{count}(確定)',
  'operation.mission.reward.confirmedRange': '1～{count}(確定)',
  'operation.mission.reward.probability': '{count}({probability}%)',
  'operation.mission.running': '遠征中',
  'operation.mission.tag.cleared': '済',
  'operation.mission.tag.combat': '交',
  'operation.mission.tag.monthly': '月',
  'operation.mission.table.kind': '種別',
  'operation.mission.table.material': '獲得資材',
  'operation.mission.table.mission': '遠征名',
  'operation.mission.table.result': '成功/大成功',
  'operation.mission.table.time': '時間',
  'operation.mission.requirement.antiAir': '対空',
  'operation.mission.requirement.antiSubmarine': '対潜',
  'operation.mission.requirement.drumShips': 'ドラム缶搭載隻数',
  'operation.mission.requirement.drums': 'ドラム缶数',
  'operation.mission.requirement.firepower': '火力',
  'operation.mission.requirement.flagshipLevel': '旗艦Lv',
  'operation.mission.requirement.flagshipType': '旗艦艦種',
  'operation.mission.requirement.search': '索敵',
  'operation.mission.requirement.shipCount': '隻数',
  'operation.mission.requirement.shipType': '艦種',
  'operation.mission.requirement.torpedo': '雷撃',
  'operation.mission.requirement.totalLevel': '合計Lv',
  'operation.resource.aria': '資源記録の表示',
  'operation.resource.chart.kit': '資材チャート:',
  'operation.resource.chart.material': '資源チャート:',
  'operation.resource.diff': '増減',
  'operation.resource.kit': '資材',
  'operation.resource.material': '資源',
  'operation.resource.range.all': '全て',
  'operation.resource.range.day': '日',
  'operation.resource.range.halfYear': '半年',
  'operation.resource.range.month': '月',
  'operation.resource.range.threeMonths': '3ヶ月',
  'operation.resource.range.week': '週',
  'operation.resource.range.year': '1年',
  'operation.resource.range.yearToDate': '今年',
  'status.assistPanel.description':
    '表示処理でエラーが発生しました。再試行しても直らない場合は、識別情報を除いた診断情報を保存して報告に添えてください。',
  'status.assistPanel.detailUnavailable': 'Error: 詳細を取得できませんでした',
  'status.assistPanel.errorDetails': 'エラー情報',
  'status.assistPanel.localPathRedacted': '[ローカルパス]',
  'status.assistPanel.phase': '処理: {phase}',
  'status.assistPanel.unavailable': '{panelTitle}を表示できませんでした',
  'status.battleHistory.empty': '出撃履歴がありません。',
  'status.battleHistory.error': '戦闘履歴を読み込めませんでした',
  'status.battleHistory.loading': '戦闘履歴検索中...',
  'status.battleScore.error': '戦果情報を読み込めませんでした。',
  'status.battleScore.loading': '戦果情報を読み込み中...',
  'status.dropDetails.error': 'ドロップ詳細を読み込めませんでした',
  'status.dropDetails.loading': 'ドロップ詳細を読み込み中...',
  'status.dropHistory.empty': '該当する履歴が見つかりません',
  'status.dropHistory.emptyFiltered': '該当する履歴が見つかりません（フィルタ指定有り）',
  'status.dropHistory.error': '履歴を読み込めませんでした',
  'status.dropHistory.loading': '履歴を取得中です...',
  'status.dropShip.empty': '該当するドロップ履歴が見つかりません',
  'status.dropShip.error': 'ドロップ履歴を読み込めませんでした',
  'status.dropShip.loading': 'ドロップ履歴を取得中です...',
  'status.dropShip.loadingForShip': '「{shipName}」のドロップ履歴を取得中です...',
  'status.dropShip.recordEmpty': '該当レコード無し',
  'status.dropShip.select': '艦名を選択するとドロップ履歴が表示されます',
  'status.invalid.line1': 'DMM ログイン後、「GAME START」画面まで自動で遷移を行います。',
  'status.invalid.line2': '「GAME START」ボタンからゲームを開始すると情報が表示されます。',
  'status.invalid.title': '艦隊情報表示',
  'status.list.mission.empty': '該当する遠征が見つかりません。',
  'status.list.ship.empty': '該当する艦船が見つかりません',
  'status.list.slotitem.empty': '該当する装備が見つかりません',
  'status.list.slotitem.selectType': '表示する装備種別を選択してください',
  'status.resourceChart.empty': '表示する資源記録がありません。',
  'status.resourceChart.error': '資源記録を読み込めませんでした。',
  'status.resourceChart.loading': '資源記録を読み込み中',
  'status.resourceChart.waiting': 'GAME START後に資源記録を読み込みます。',
  'status.timelineScore.beforeGame': 'GAME開始前により戦果チャートが表示できません',
  'status.timelineScore.empty': '当月戦果データがありません。',
  'status.timelineScore.error': '当月戦果データの取得に失敗しました。',
  'status.timelineScore.loading': '当月戦果データを取得中...',
  'status.workspace.configurePanels': 'パネルを配置',
  'status.workspace.deleteEmptyPage': 'このページを削除',
  'status.workspace.deleteEmptyPageTitle': 'この空のページを削除',
  'status.workspace.lastPageCannotDelete': '最後のページは削除できません',
  'status.workspace.noPanels': 'このページに表示するパネルはありません。',
  'timeline.quest.title': '遂行中任務',
  'timeline.quest.summary': '遂行中: {active} 受託可能: {capacity}',
  'timeline.quest.unavailable': 'クエスト情報が未取得です。任務(クエスト)画面を開いてください。',
  'timeline.quest.completed': '達成',
  'timeline.gimmick.title': 'ギミック',
  'timeline.gimmick.soundDetected': 'ギミック解除音を検知しました。',
  'timeline.gimmick.mapChangeTitle': '海域変化ギミック',
  'timeline.gimmick.mapChangeDetected': '海域変化を検知しました。',
  'timeline.lastBattle': '直近戦闘 {battle}',
  'timeline.score.today': '当日戦果',
  'timeline.score.total': '累積戦果',
  'timeline.sortieHistory': '出撃履歴',
  'timeline.motherPortFull': '母港FULL',
  'timeline.airSearch': '航空偵察：{result}',
  'timeline.noBattle': '戦闘なし',
  'timeline.airState.0': '制空均衡',
  'timeline.airState.1': '制空権確保',
  'timeline.airState.2': '航空優勢',
  'timeline.airState.3': '航空劣勢',
  'timeline.airState.4': '制空権喪失',
  'test.layout.hpGauge': '艦隊HP表示レイアウトテスト',
  'test.layout.fleetStatus': '艦隊ステータス領域',
  'workspace.aria.primaryPanels': '主画面パネル',
  'workspace.aria.secondaryPanels': '補助パネル',
  'workspace.page.add': 'ページを追加',
  'workspace.layout.button': '配置',
  'workspace.layout.changedSuffix': '・変更済',
  'workspace.layout.title': 'パネル配置',
  'workspace.layout.changedTitle': 'パネル配置（変更済）',
  'workspace.layout.editorAria': 'パネル配置',
  'workspace.layout.editorTitle': '{page}のパネル配置',
  'workspace.page.name': 'ページ名',
  'workspace.page.duplicate': '複製',
  'workspace.page.delete': '削除',
  'workspace.page.deleteTitle': 'ページを削除',
  'workspace.layout.help':
    '表示、順序、幅、高さを変更できます。すべて非表示にしても、上の「配置」から再表示できます。各パネル右下の「↘」をドラッグしてサイズを変更できます。変更は自動保存されます。',
  'workspace.layout.showAll': 'すべて表示',
  'workspace.layout.hideAll': 'すべて非表示',
  'workspace.layout.moveEarlier': '前へ移動',
  'workspace.layout.moveLater': '後ろへ移動',
  'workspace.layout.panelWidth': 'パネル幅',
  'workspace.layout.panelHeight': 'パネル高さ',
  'workspace.layout.fullWidth': '全幅',
  'workspace.layout.widthValue': '幅 {width}/12',
  'workspace.layout.heightValue': '高さ {height}',
  'workspace.hiddenPages': '非表示のページ',
  'workspace.restorePage': '再表示',
  'workspace.resetAll': '全体を初期配置に戻す',
  'workspace.resizePreview': '幅 {width}/12・高さ {height}',
  'workspace.resizeAria': 'パネルサイズを変更',
  'workspace.resizeTitle': 'ドラッグしてパネルサイズを変更',
  'workspace.confirm.deleteUserPage': '「{page}」を削除しますか？',
  'workspace.confirm.deleteEmptyUserPage': '空のページ「{page}」を削除しますか？',
  'workspace.confirm.hideEmptyBuiltInPage':
    '空のページ「{page}」をタブから削除しますか？後で配置画面から再表示できます。',
  'workspace.confirm.resetAll': '作成したページを含むすべてのパネル配置を初期状態に戻しますか？',
  'titlebar.assist.show': 'アシストを表示',
  'titlebar.devtools.app': 'デベロッパー ツール',
  'titlebar.devtools.game': 'Game側デベロッパー ツール',
  'titlebar.layout.classic': 'クラシック表示に戻す',
  'titlebar.layout.workspace': 'ワークスペース表示に切り替える',
  'titlebar.maximize.toggle': '最大化を切り替える',
  'titlebar.mute.off': 'サウンドはオフ状態',
  'titlebar.mute.on': 'サウンドはオン状態',
  'titlebar.option': '設定',
  'titlebar.reload': 'ページを再読み込みします',
  'titlebar.secondaryWindow.open': '新しいアシストウインドウを表示',
  'titlebar.status.battleEmpty': '戦闘情報がありません',
  'titlebar.status.sortieEmpty': '出撃情報がありません',
  'titlebar.status.sortieInProgress': '出撃中',
  'titlebar.status.sortieReturning': '出撃帰',
  'titlebar.status.gimmick': 'ギミック',
  'titlebar.status.clearSound': '解除音',
  'titlebar.status.detected': '有',
  'titlebar.status.unsupplied': '未補給',
  'titlebar.status.fleet.1': '第一',
  'titlebar.status.fleet.2': '第二',
  'titlebar.status.fleet.3': '第三',
  'titlebar.status.fleet.4': '第四',
  'titlebar.status.airbaseUnsupplied': '基地未補給',
  'titlebar.status.waySupport': '前衛支援',
  'titlebar.status.bossSupport': '決戦支援',
  'titlebar.status.sortied': '出',
  'titlebar.timeline': 'タイムライン',
  'titlebar.score': '戦果',
  'titlebar.topmost': '常に最前面に表示する',
  'titlebar.update.available': '更新があります。',
  'titlebar.update.versionAvailable': '更新があります。バージョン {version} が利用可能です。',
  'update.button.check': '更新をチェック',
  'update.button.download': '更新をダウンロード',
  'update.button.restart': '再起動',
  'update.error.checkFailed': '更新チェックに失敗しました',
  'update.error.downloadFailed': '更新に失敗しました',
  'update.error.restartFailed': '再起動に失敗しました',
  'update.heading': '更新チェック',
  'update.includeBeta': 'Beta版(開発版)を更新チェック対象に含める',
  'update.onStartup': '起動時に更新チェックを行う',
  'update.state.available': '更新が見つかりました。バージョン {version} が利用可能です。',
  'update.state.checking': '更新をチェック中...',
  'update.state.downloading': '更新をダウンロード中...',
  'update.state.downloadingPercent': '更新をダウンロード中... {percent}%',
  'update.state.error': '更新チェックでエラーが発生しました。',
  'update.state.errorWithDetail': '更新チェックエラー ({message})',
  'update.state.latest': '最新バージョンを使用中です。',
  'update.state.ready': '更新の準備が整いました。再起動すると更新が適用されます。',
  'update.state.readySubtext': 'または、アプリケーション終了時に更新が適用されます。'
} as const)

export type AppMessageKey = keyof typeof JapaneseMessages

type PlaceholderNames<Text extends string> = Text extends `${string}{${infer Name}}${infer Rest}`
  ? Name | PlaceholderNames<Rest>
  : never

export type AppMessageParameters<Key extends AppMessageKey> = Readonly<
  Record<PlaceholderNames<(typeof JapaneseMessages)[Key]>, MessageParameter>
>

export type TranslationOptions<Key extends AppMessageKey> = [
  PlaceholderNames<(typeof JapaneseMessages)[Key]>
] extends [never]
  ? {
      readonly locale?: LocalizationLocale
      readonly params?: never
    }
  : {
      readonly locale?: LocalizationLocale
      readonly params: AppMessageParameters<Key>
    }

export type TranslationArguments<Key extends AppMessageKey> = [
  PlaceholderNames<(typeof JapaneseMessages)[Key]>
] extends [never]
  ? [options?: TranslationOptions<Key>]
  : [options: TranslationOptions<Key>]

export type BoundTranslationOptions<Key extends AppMessageKey> = [
  PlaceholderNames<(typeof JapaneseMessages)[Key]>
] extends [never]
  ? {
      readonly params?: never
    }
  : {
      readonly params: AppMessageParameters<Key>
    }

export type BoundTranslationArguments<Key extends AppMessageKey> = [
  PlaceholderNames<(typeof JapaneseMessages)[Key]>
] extends [never]
  ? [options?: BoundTranslationOptions<Key>]
  : [options: BoundTranslationOptions<Key>]

export type AppTranslator = <Key extends AppMessageKey>(
  key: Key,
  ...options: BoundTranslationArguments<Key>
) => string

const PlaceholderPattern = /\{([A-Za-z][A-Za-z0-9_]*)\}/g

export function normalizeAppLocale(value: unknown): AppLocale {
  return AppLocales.includes(value as AppLocale) ? (value as AppLocale) : 'ja-JP'
}

function resolveIntlLocale(locale: LocalizationLocale): AppLocale {
  return locale === InternalPseudoLocale ? 'ja-JP' : normalizeAppLocale(locale)
}

function requireFiniteNumber(value: number, label: string): void {
  if (!Number.isFinite(value)) {
    throw new RangeError(`${label} must be a finite number`)
  }
}

export function formatAppNumber(
  value: number,
  locale: LocalizationLocale = 'ja-JP',
  options?: Intl.NumberFormatOptions
): string {
  requireFiniteNumber(value, 'localized number')
  return new Intl.NumberFormat(resolveIntlLocale(locale), options).format(value)
}

export function formatAppDateTime(
  value: Date | number,
  locale: LocalizationLocale = 'ja-JP',
  options?: Intl.DateTimeFormatOptions
): string {
  const timestamp = value instanceof Date ? value.getTime() : value
  requireFiniteNumber(timestamp, 'localized date')
  return new Intl.DateTimeFormat(resolveIntlLocale(locale), options).format(value)
}

export function formatAppRelativeTime(
  value: number,
  unit: Intl.RelativeTimeFormatUnit,
  locale: LocalizationLocale = 'ja-JP',
  options?: Intl.RelativeTimeFormatOptions
): string {
  requireFiniteNumber(value, 'localized relative time')
  return new Intl.RelativeTimeFormat(resolveIntlLocale(locale), options).format(value, unit)
}

export function selectAppPluralCategory(
  value: number,
  locale: LocalizationLocale = 'ja-JP',
  options?: Intl.PluralRulesOptions
): Intl.LDMLPluralRule {
  requireFiniteNumber(value, 'localized plural value')
  return new Intl.PluralRules(resolveIntlLocale(locale), options).select(value)
}

export function formatLocalizedMessage(template: string, params: MessageParameters = {}): string {
  const placeholderNames = new Set(
    [...template.matchAll(PlaceholderPattern)].map((match) => match[1])
  )
  const parameterNames = Object.keys(params)
  const missing = [...placeholderNames].filter(
    (name) => !Object.prototype.hasOwnProperty.call(params, name)
  )
  const unexpected = parameterNames.filter((name) => !placeholderNames.has(name))
  const invalid = parameterNames.filter((name) => {
    const value = params[name]
    return (
      (typeof value !== 'string' && typeof value !== 'number') ||
      (typeof value === 'number' && !Number.isFinite(value))
    )
  })
  if (missing.length > 0 || unexpected.length > 0 || invalid.length > 0) {
    throw new Error(
      `localized message parameters do not match: missing=${missing.join(',')}; ` +
        `unexpected=${unexpected.join(',')}; invalid=${invalid.join(',')}`
    )
  }

  return template.replace(PlaceholderPattern, (_placeholder, name: string) => String(params[name]))
}

export function pseudoLocalizeTemplate(template: string): string {
  let cursor = 0
  let expanded = ''
  for (const match of template.matchAll(PlaceholderPattern)) {
    const index = match.index ?? 0
    expanded += expandPseudoText(template.slice(cursor, index))
    expanded += match[0]
    cursor = index + match[0].length
  }
  expanded += expandPseudoText(template.slice(cursor))
  return `［${expanded}］`
}

function expandPseudoText(text: string): string {
  return [...text]
    .map((character) => (/\s/u.test(character) ? character : character + character))
    .join('')
}

export function translateAppMessage<Key extends AppMessageKey>(
  key: Key,
  ...options: TranslationArguments<Key>
): string {
  const option = options[0]
  const locale = option?.locale ?? 'ja-JP'
  const template =
    locale === InternalPseudoLocale
      ? pseudoLocalizeTemplate(JapaneseMessages[key])
      : JapaneseMessages[key]
  return formatLocalizedMessage(template, option?.params)
}

export function createAppTranslator(resolveLocale: () => LocalizationLocale): AppTranslator {
  return ((key: AppMessageKey, option?: { readonly params?: MessageParameters }) => {
    const locale = resolveLocale()
    const template =
      locale === InternalPseudoLocale
        ? pseudoLocalizeTemplate(JapaneseMessages[key])
        : JapaneseMessages[key]
    return formatLocalizedMessage(template, option?.params)
  }) as AppTranslator
}
